### ISSUE TITLE
"openFile: does not exist" when test source files cannot be found

### ISSUE THREAD

**Issue by chris-martin** [hedgehogqa/haskell-hedgehog#105]
I just did a quick test with hedgehog-0.5 in GHCi and saw some odd behavior:

```
λ> check $ property $ forAll (Gen.integral $ Range.exponential 1 1024) >>= \x -> x + 1 === x
  ↯ <interactive> failed after 1 test (shrinking)
*** Exception: <interactive>: openFile: does not exist (No such file or directory)
```

Why is hedgehog trying to open a file?

**Comment by jystic** [comment]
>  Why is hedgehog trying to open a file?

good question!! 😲

**Comment by chris-martin** [comment]
Just to confirm that it's not something related to my GHCi config:

```
❯❯❯ stack repl --ghc-options -ignore-dot-ghci
Configuring GHCi with the following packages:
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /tmp/ghci2395/ghci-script
Prelude> import Hedgehog
Prelude Hedgehog> import qualified Hedgehog.Range as Range
Prelude Hedgehog Range> import qualified Hedgehog.Gen as Gen
Prelude Hedgehog Range Gen> check $ property $ forAll (Gen.integral $ Range.exponential 1 1024) >>= \x -> x + 1 === x
  ↯ <interactive> failed after 1 test (shrinking)
*** Exception: <interactive>: openFile: does not exist (No such file or directory)
```

**Comment by jystic** [comment]
Oh actually, silly me! Of course it reads files, it's trying to [get the source code](https://github.com/hedgehogqa/haskell-hedgehog/blob/a506b6d2ec9b8721aead61b72a2f1fa8b4c88ce5/hedgehog/src/Hedgehog/Internal/Discovery.hs#L40) to display the error message, but in this case the file is`<interactive>` as the whole property is on the repl.

**Comment by jystic** [comment]
I think I need to detect this situation and just display the error message like we do for 7.10, with the source code annotations.

**Comment by kquick** [comment]
I recommend removing the "in GHCI" on the title for this bug.

    $ cabal build
    $ cd src
    $ ../dist/build/mytest/mytest
    mytest: test/TestStuff.hs: openFile: does not exist (No such file or directory)
    $

It's not clear what the right heuristic is for this: allow an ENVVAR/arg to specify the source root?  automatically search upward for the cabal file and/or dist root?  Output a message explaining why source code annotations are not available?

**Comment by jystic** [comment]
Yeah searching around sounds like a good idea, as is outputting a better error message

**Comment by tmcdonell** [comment]
+1

My use case is that I have a bunch of tests exported by one library (accelerate) so that they can be reused by several others (the backends). These are all in separate packages though, hence it can't find the source later on.

Environment variable to specify the source root(s) to search?

**Comment by tmcdonell** [comment]
What about a template-haskell version of `property` which saves the code for the body at TH time?

**Comment by jystic** [comment]
> What about a template-haskell version of property which saves the code for the body at TH time?

That's a neat idea, we actually already have the splice `$(discover)`, are you using that? If so maybe we could pull the source code in that splice?

**Comment by tmcdonell** [comment]
I am not using `$(discover)`; I am currently using `tasty`+`tasty-hedgehog` as the runner.

As an example though, the tests all look something [like this](https://github.com/AccelerateHS/accelerate/blob/cffae80c232049ab69d0336f81e3c70add0e1689/src/Data/Array/Accelerate/Test/NoFib/Prelude/Map.hs#L146).

**Comment by jystic** [comment]
Ok, so yeah, a special version of `property` would indeed work.

The corner case is when you are looking for the source code for other files in the project, how can we find those? Maybe we can have a global store for the whole package somehow?

**Comment by thumphries** [comment]
Got some verbal reports today of this showing up when you try to run `hedgehog-example` in GHCi

Wondering if just handling the exceptions in `readFile` would do the trick?

**Comment by thumphries** [comment]
With the change in #184 I think this failure mode is gone, so I'll close the ticket, feel free to reopen if it appears again.

Trevor's problem is still around, if you export tests across package lines they will not come with the shiny error reporting. They will still run and produce the 7.10 style report.
