### ISSUE TITLE
Adjusting ranges

### ISSUE THREAD

**Issue by newhoggy** [hedgehogqa/haskell-hedgehog#106]
I'd like to be able to write a generator:

```
genIdentifier :: MonadGen m => Range Int -> m String
genIdentifier range = ...
```

It should produce an identifier of the length constrained by `range`, but the first character ought to be lower case letter, and the remainder can be a mixture of lower and upper case letters and numbers.

Intuitively, I should be able to generate the first character and remainder separately and combine them, but I don't know how to adjust the range to reduce it by `1`:

```
genIdentifier :: MonadGen m => Range Int -> m String
genIdentifier range = do
   a <- Gen.lower
   as <- Gen.string (range `subtract` 1) Gen.alphaNum
   return (a:as)
```

Does the Hedgehog public API have a way to do this?

Also is it recommended not to do this?

Thanks!

**Comment by jystic** [comment]
`Range` is a functor, so you could try ```fmap (`subtract` 1) range```

**Comment by newhoggy** [comment]
This resolves my issues.  Thanks for your help!

```
λ> bounds 999 (linear 100 200)
(100,200)
λ> bounds 999 ((\i -> i - 1) <$> linear 100 200)
(99,199)
```
