### ISSUE TITLE
Need a way to set maximum time limit for property test

### ISSUE THREAD

**Issue by newhoggy** [hedgehogqa/haskell-hedgehog#114]
It's possible sometimes for a test function to not terminate.  In such cases, it would be useful to timeout the test because if the tested function does not terminate, then hedgehog will not print the generated values that cause non-termination.

**Comment by glaebhoerl** [comment]
I think this is the same as #211 (which is newer but has more discussion)?

**Comment by moodmosaic** [comment]
Closing in favour of #211, where the workarounds are collected.
