### ISSUE TITLE
commitAndReleaseBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by nodew** [hedgehogqa/haskell-hedgehog#117]
```
━━━ Check.Functor ━━━
  koan-test.exe: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
  ○ 0/5 complete (running)
Completed 2 action(s).
Test suite failure for package hw-koans-0.1.0.0
    koan-test:  exited with: ExitFailure 1
Logs printed to console
```
https://github.com/haskell-works/hw-koans.git  

when I run test with this project. I get this error `commitAndReleaseBuffer: invalid argument (invalid character)`
platform: windows10 powershell
ghc: 8.0.2

unfortunately, I don't have a linux machine or mac nearby, so I'm not sure whether the problem is caused by windows 10 or not.

**Comment by moodmosaic** [comment]
This is probably related to #32, and perhaps #110 too. As per [this](https://github.com/hedgehogqa/haskell-hedgehog/issues/110#issuecomment-318644107) comment, you may try these:

```
hSetEncoding stdout utf8
hSetEncoding stderr utf8
```
