### ISSUE TITLE
Duplicates in shrink trees for maybe

### ISSUE THREAD

**Issue by enolan** [hedgehogqa/haskell-hedgehog#118]
The shrink tree for this generator contains several duplicates:
```
$ stack ghci --package hedgehog --resolver lts-9.2
Configuring GHCi with the following packages: 
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /tmp/ghci18165/ghci-script
Prelude> import Hedgehog
Prelude Hedgehog> import qualified Hedgehog.Gen as Gen
Prelude Hedgehog Gen> Gen.print $ Gen.maybe Gen.latin1
=== Outcome ===
Just 'T'
=== Shrinks ===
Nothing
Just 'T'
Just 'T'
Just 'T'
Just 'T'
Just '\NUL'
Just '*'
Just '?'
Just 'J'
Just 'O'
Just 'R'
Just 'S'
```

This slows down shrinking a lot. I think the culprit is `maybe`, you get reasonable shrinks from `latin1` on its own.

**Comment by jystic** [comment]
I'm not sure how to avoid this in the generators themselves, but perhaps we can build some things in to the tree to prevent duplicate entries if you're finding that shrinking is slowed down a lot by this.

**Comment by TysonMN** [comment]
@HuwCampbell said in https://github.com/hedgehogqa/haskell-hedgehog/pull/406#issuecomment-709617637 that issue was fixed by that PR.  Does someone want to test if this issue is gone?

**Comment by moodmosaic** [comment]
@TysonMN, here are some sample outputs:

```
λ Gen.print $ Gen.maybe Gen.latin1
=== Outcome ===
Just '@'
=== Shrinks ===
Nothing
Just '\NUL'
Just ' '
Just '0'
Just '8'
Just '<'
Just '>'
Just '?'
```

```
λ Gen.print $ Gen.maybe Gen.latin1
=== Outcome ===
Just 'S'
=== Shrinks ===
Nothing
Just '\NUL'
Just '*'
Just '?'
Just 'I'
Just 'N'
Just 'Q'
Just 'R'
```

It appears that #406 closes this one.
