### ISSUE TITLE
Ranges not working as expected

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#120]
Currently see:
```
λ > Gen.sample $ Gen.list (Range.singleton 100) (Gen.int $ Range.linear 0 10)
[0,0,2,0,1,2,1,1,2,0,0,2,1,3,3,2,0,1,3,0,2,2,3,0,0,2,1,3,0,3,3,2,3,0,0,1,2,1,0,3,2,1,2,1,2
,1,3,3,3,0,3,3,1,1,0,2,0,0,0,1,1,3,3,3,1,3,3,3,3,1,2,0,1,1,2,0,0,1,1,3,0,0,0,1,1,2,0,2,2,3
,1,3,1,0,2,1,1,0,2,0]
```
I'd expect to see a few more values in the range `[4 .. 10]` from that generator.

**Comment by erikd** [comment]
Its got something to do with how `Size` is handled. I can "fix" this by doing:
```
Gen.sample $ Gen.scale (* 10) $ Gen.list (Range.singleton 100) (Gen.int $ Range.linear 0 10)
```
but the current behavior (ie without adding the explicit scaling operation) is rather surprising.

**Comment by jystic** [comment]
This is because `Gen.sample` always uses a size of `30` (from memory)

You won't see this behaviour when running actual tests, which use all sizes from `0` to `99`

**Comment by jystic** [comment]
Similar to what you were doing, the way to use sample with a specific custom size is `Gen.resize`:
```hs
Gen.sample $ Gen.resize 99 $ Gen.list (Range.singleton 100) (Gen.int $ Range.linear 0 10)
```

**Comment by erikd** [comment]
This problem is independent of `Gen.sample`.

I found this odd behavior when doing `Gen.integral_ (Range.linear 0 10)` and noticed I was never getting values above `3` out of the generator. I was sort of expecting a uniform distribution across the specified range.

I've even written a test :
```
prop_generate_full_range :: Property
prop_generate_full_range = property $ do
  upper <- forAll $ Gen.int $ Range.linear 1 20
  list <- forAll $ Gen.list (Range.singleton $ 100 * upper) (Gen.int $ Range.linear 0 upper)
  List.nub (List.sort list) === [0 .. upper]
```
which should pass if the the `Gen.int` generator generates uniformly distributed values. This test currently fails.

**Comment by jystic** [comment]
If you want a distribution which is unaffected by the size you need to use `Range.constant 0 10`.

`Range.linear 0 10` slowly scales up the upper bound as the size of the test increases. So when the size is `0` it will have a range of `0` to `0` and your test won't pass.

I explain how this works in [my lambda jam talk](https://www.youtube.com/watch?v=AIv_9T0xKEo&feature=youtu.be&t=18m55s) from 18:55 to 23:00 if you're interested.

**Comment by erikd** [comment]
Ah, thats got it. Thanks!
