### ISSUE TITLE
The reporting is wrong if `property` is encapsulated in another function call

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#123]
I have an alias for `testProperty` in a `Test.Tasty.Extensions` module:
```haskell
prop :: HasCallStack => TestName -> PropertyT IO () -> TestTree
prop name p = testProperty name (HH.property p)
```
Unfortunately, this results in a trace showing the content of that file when there is a failure instead of the content of my original assertion:
![image](https://user-images.githubusercontent.com/10988/31928628-1a11d76c-b899-11e7-98d0-3414db78b59b.png)

I am not sure what can really be done about this, do you have any idea @jystic?

**Comment by thumphries** [comment]
I've worked around this using `GHC.Stack.withFrozenCallStack`, which is how internal Hedgehog combinators do it.

**Comment by etorreborre** [comment]
Thanks Tim, I am definitely making some progress with this! The only case it doesn't work is with properties involving `IO` (`test` is an alias for `prop` executing only once):
```haskell
test_getEvents = test "getEvents returns the list of events for a given event type" $
  -- some IO call
  let allEvents = undefined :: IO (Either String [Event])
  in do evs <- lift allEvents
        isRight evs

isRight :: (Show a, MonadTest m) => Either a b -> m ()
isRight (Right _) = pure ()
isRight (Left v) =
  annotate ("the value is a Left" <> show v) >>
  failure
```

Then this prints
```
test_getEvents = test "getEvents returns the list of events for a given event type" $
         ┃ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
On the other hand a non-IO test works fine:
```haskell
test_getEvents = test "getEvents returns the list of events for a given event type" $
  -- some IO call
  let allEvents = undefined :: IO (Either String [Event])
  in True === False
```
This results in 
```
in True === False
         ┃   ^^^^^^^^^^^^^^^^^
         ┃   │ Failed (- lhs =/= + rhs)
```
Do you understand why?

**Comment by etorreborre** [comment]
This is indeed working a lot better. Thanks!
