### ISSUE TITLE
Observe test case distribution

### ISSUE THREAD

**Issue by bitemyapp** [hedgehogqa/haskell-hedgehog#127]
https://hackage.haskell.org/package/QuickCheck-2.10.1/docs/Test-QuickCheck-Property.html#v:classify

Example: http://hackage.haskell.org/package/checkers-0.4.9.5/docs/src/Test-QuickCheck-Utils.html#isCommutable

```haskell
isTotalOrder :: (Arbitrary a,Show a,Ord a) => a -> a -> Property
isTotalOrder x y =
    classify (x > y)  "less than" $
    classify (x == y) "equals" $
    classify (x < y)  "greater than" $
    x < y || x == y || x > y
```

**Comment by bitemyapp** [comment]
https://hackage.haskell.org/package/QuickCheck-2.10.1/docs/Test-QuickCheck-Property.html#v:cover

**Comment by mbrock** [comment]
It seems hard to feel confident in property tests without something like this, no? Especially when input domains are large and there's some class of rare cases that you still want to make sure are represented.

**Comment by thumphries** [comment]
Not really; if you have rare cases with unusual significance you can write a separate generator and properties exercising them.

Coverage tooling would be a great addition to Hedgehog; none of us really use it in QuickCheck so it has been a low priority. PRs welcome

**Comment by mankyKitty** [comment]
I have a basic implementation of such a thing: https://github.com/qfpl/tasty-hedgehog-coverage 

Happy to try to make this into a more useful "built-in" part of Hedgehog, if there's interest.

**Comment by ruhatch** [comment]
@thumphries is the approach taken in `tasty-hedgehog-coverage` good enough to make it into `hedgehog` proper? I'd be happy to submit a PR to try and combine them

**Comment by mankyKitty** [comment]
@ruhatch Happy to help if required, feel free to throw issues/PRs at `tasty-hedgehog-coverage` too.

**Comment by moodmosaic** [comment]
Resolved via https://github.com/hedgehogqa/haskell-hedgehog/pull/253, https://github.com/hedgehogqa/haskell-hedgehog/pull/262, https://github.com/hedgehogqa/haskell-hedgehog/pull/288, and https://github.com/hedgehogqa/haskell-hedgehog/pull/289.
