### ISSUE TITLE
/=== operator

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#138]
I am not sure that `/===` is a valid syntax but this would be helpful to show that 2 values should not be equal. My current workaround is
```
(left, right, left == right) === (left, right, False)
```

**Comment by thumphries** [comment]
`(/==)` or `(/===)` is indeed valid operator syntax.

I think we've talked about adding `neg` or similar before, it just hasn't happened.

**Comment by amrhassan** [comment]
I see this is in `master` already. Any chance we can get a new release? :smiley:

**Comment by thumphries** [comment]
This is indeed in master; unsure about release schedule

**Comment by etorreborre** [comment]
Who should we ping about this? Who is usually doing the releases?

**Comment by moodmosaic** [comment]
@jystic
