### ISSUE TITLE
No HegdeHog on lts-10.3 ? 

### ISSUE THREAD

**Issue by rwobben** [hedgehogqa/haskell-hedgehog#143]
According to this page ( https://www.stackage.org/package/hedgehog ) 
hedgehog schould be avaible on lts-10.3 

But when I add hegdehog to the depencencies part I see this message : 

error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for Trivial-0.1.0.0:
    hegdehog must match -any, but the stack configuration has no specified version

Also adding hedgehog-1.5.3 to the extra-deps does not solve this. 
and stack solver gives this output : 

Could not parse cabal-install errors:

>>>> Cabal errors begin
CallStack (from HasCallStack):
  die', called at .\Distribution\Client\Install.hs:240:21 in main:Distribution.Client.Install
cabal.EXE: Could not resolve dependencies:
rejecting: Trivial-0.1.0.0:!test (constraint from config file, command line
flag, or user target requires opposite flag selection)
trying: Trivial-0.1.0.0:*test
unknown package: hegdehog (dependency of Trivial-0.1.0.0:*test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: Trivial-0.1.0.0:test (4), Trivial (3),
hegdehog (1)
<<<< Cabal errors end

CallStack (from HasCallStack):
  error, called at src/Stack\Solver.hs:130:25 in stack-1.6.3-F6YVX3qh2MsHZufmhdWM8J:Stack.Solver

I work on Windows 10 with stack 10.3 

Roelof

Edit 1 : When I do  stack install hedgehog , hegdehog gets installed

**Comment by thumphries** [comment]
> unknown package: hegdehog (dependency of Trivial-0.1.0.0:*test)

This looks like a typo to me, what happens when you flip the `g` and `d`?

**Comment by rwobben** [comment]
Chips  then I had that problem.  Sorry for the bug report

**Comment by thumphries** [comment]
No problem, hope you're enjoying Hedgehog!

**Comment by rwobben** [comment]
I hope also, now trying to find out how to make hedgehog-checkers work so I can test for things like monad laws
