### ISSUE TITLE
Async dependencies

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#164]
Hi, I have some conflicting dependencies in my build because one of my main dependencies is forcing `async-timer >=0.2.0.0 && <0.3` and `async >=2.2.1 && <2.3`. But this conflicts with hedgehog.

Is it reasonable to ask for hedgehog `0.6.0.0` to be released with upgraded `async` dependencies? Would you accept a PR for this?

**Comment by nhibberd** [comment]
It should be fine to upgrade the upper bounds in hedgehog

**Comment by etorreborre** [comment]
I did a small [PR](https://github.com/hedgehogqa/haskell-hedgehog/pull/165). If the build passes I can assume that everything is fine?
