### ISSUE TITLE
ReadMe sample code crashes at run-time

### ISSUE THREAD

**Issue by ploeh** [hedgehogqa/haskell-hedgehog#178]
I'm trying to follow the code examples in the ReadMe file, but it throws an exception at run time:

```
*Q49343774 Q49343774> tests
*** Exception: <stdout>: hPutChar: invalid argument (invalid character)
```

FWIW, I tried to simplify the file even further in order to troubleshoot if something else could be the matter:

```haskell
{-# LANGUAGE TemplateHaskell #-}
module Q49343774 where

import Hedgehog

prop_reverse :: Property
prop_reverse =
  property $ do
    True === True

tests :: IO Bool
tests =
  checkParallel $$(discover)

foo :: () -> String
foo () = "foo"
```

The reason I included the `foo` function was that I wanted to verify that there isn't something fundamentally wrong with the file, such as a non-printable character that GHCi would choke on. That doesn't seem to be the case:

```
*Q49343774 Q49343774> foo ()
"foo"
```

My environment:

- **Operating System:** Windows 10 Pro x64, Version 1709, Build 16299.371
- **Stack:** 1.6.3
- **GHC:** 8.2.2

Am I doing anything wrong? Is there something I can do to troubleshoot?

**Comment by moodmosaic** [comment]
See https://github.com/hedgehogqa/haskell-hedgehog/issues/110#issuecomment-318763249 for a workaround.

**Comment by moodmosaic** [comment]
I've originally reported this in https://github.com/hedgehogqa/haskell-hedgehog/issues/32, and the discussion continues in #110 (which shows at least two workarounds).

I haven't investigated further what might be causing this, since I've moved to *nix since then. Perhaps we should close this in favor of #110(?)

**Comment by ploeh** [comment]
Thank you for your help 👍 

The workarounds enable me to get code running, but this hardly seems like a satisfactory solution. While I grant that there's small issues with QuickCheck tests on Windows as well (or, at least, on my system), they're nowhere near as conspicuous as these.

ATM, it's not clear to me at all why this problem exists, but if I can do something to help address it, I'd like to offer to spend a few hours doing so, but I'm going to need some guidance.

Whether you want to close this issue in favour of another I have no opinion. Feel free to close this issue if you feel the other one better captures the problem; I can't evaluate whether or not that's the case.

**Comment by thumphries** [comment]
Yeah, nobody who works on Hedgehog uses Windows right now, so it is hard for us to resolve. We'd love for someone to spend time on it, though. We might be able to add the transliteration hack to the library (it's good enough for GHC) - or follow one of the other avenues in #110.

Closing in favour of #110, where the workarounds are collected.

**Comment by moodmosaic** [comment]
>Well, now, at least, it runs, but pretty it isn't:
>
>```
>*Q49343774 Q49343774> :m +System.IO
>*Q49343774 Q49343774 System.IO> hSetEncoding stdout utf8
>*Q49343774 Q49343774 System.IO> hSetEncoding stderr utf8
>*Q49343774 Q49343774 System.IO> tests
>ΓöüΓöüΓöü Q49343774 ΓöüΓöüΓöü
>  Γ£ô prop_reverse passed 100 tests.
>  Γ£ô 1 succeeded.
>True
>```

@ploeh, if you execute `chcp 65001` in the console the output should be fine. See https://github.com/hedgehogqa/haskell-hedgehog/issues/110#issuecomment-397785931.

**Comment by ploeh** [comment]
Thanks, but

```
$ chcp 65001
bash: chcp: command not found
```

**Comment by moodmosaic** [comment]
Weird... Are you using the Windows Subsystem for Linux or just the Git Bash?

**Comment by moodmosaic** [comment]
You should enter this in a regular command prompt (cmd.exe) since it's a Windows command, and then start Git Bash from there - - or just use ConEmu which takes care of all this.

**Comment by ploeh** [comment]
Turns out that it's a `.com` file, not an `.exe`. It can be called by writing `chcp.com` instead of just `chcp`. It makes the output of the test better, although still not good:

![image](https://user-images.githubusercontent.com/242165/41496479-52c619b8-7141-11e8-9158-9c7684eff097.png)

**Comment by moodmosaic** [comment]
Did you also set stdout/err encoding to UTF-8 as per https://github.com/hedgehogqa/haskell-hedgehog/issues/110#issuecomment-397785931?

**Comment by ploeh** [comment]
I've tried with and without. It makes no difference.

**Comment by moodmosaic** [comment]
When I have to use Windows, I use the stable version of https://conemu.github.io

In the gif I posted, I'm using the latest stable version of ConEmu: https://conemu.github.io

Perhaps ConEmu deals with UTF-8 far better than cmd.exe

(There are other benefits of using ConEmu anyway.)

**Comment by ploeh** [comment]
I just tried in cmd instead of Bash. Same problem. I wonder if it's just my system that behaves strangely.

I'll try on another machine...

**Comment by moodmosaic** [comment]
I wonder if it's the Danish locale (but I'm using the Greek locale so it shouldn't matter).

Still, I'd be curious to see what happens if you try running a Git Bash from inside ConEmu on that machine...

**Comment by ploeh** [comment]
> Perhaps ConEmu deals with UTF-8 far better than cmd.exe

Most likely. Git bash handles this quite poorly, so it's unlikely to get much worse, one could hope. For the last many months, I haven't had the mental bandwidth to look into new tooling, but for the next month or so, I hope that'll change. If so, this is high on my list of things to look at.

> I wonder if it's the Danish locale

I wonder the same 😄

**Comment by ploeh** [comment]
Tried all the above variations on another machine. Same result 😢 

Those two machines aren't that different, though. For instance, both run Danish locale. In many ways, I try to keep them in sync with each other...

**Comment by moodmosaic** [comment]
So when I'm on Windows, I run ConEmu, GHCi, and a code editor, like this:

![haskell-hedgehog-issue-110-b-speed](https://user-images.githubusercontent.com/287532/41497158-96ff1672-7158-11e8-9129-c447ac513d83.gif)

Notice that I run `chcp` from inside GHCi via `:! chcp 65001`, because I spend almost *all* my time in GHCi, so even things like git, hoogle, etcetera I run them from inside GHCi as well (e.g. `:! git status`). :sweat_smile:

**Comment by moodmosaic** [comment]
@ploeh, even more interesting news.

As an alternative to the built-in Windows command prompt (cmd.exe), ConEmu and Cmder, one can simply use the terminal inside VSCode by setting to a *Git Bash*:

![image](https://user-images.githubusercontent.com/287532/41704277-81490ccc-753e-11e8-8bbe-f025d84973fb.png)
