### ISSUE TITLE
Variant?

### ISSUE THREAD

**Issue by bitemyapp** [hedgehogqa/haskell-hedgehog#180]
I'm looking into porting a `CoArbitrary` equivalent to Hedgehog so that I can drop this module: https://github.com/bitemyapp/hedgehog-checkers/blob/master/hedgehog-checkers/src/Hedgehog/Checkers/Ugly/Function/Hack.hs

The recursion of dependencies from the typical CoArbitrary instance brings me to variant, TFGen, etc. I don't want to repeat any work that's already been done, is `variant :: Integral n => n -> Gen a -> Gen a` not a thing or did I just miss it somewhere?

**Comment by thumphries** [comment]
I don't think you missed anything. There's nothing completely equivalent to `variant` (or any of the CoArbitrary machinery). It's another one of those QC features none of us use very much, so it is hard to come up with a thoughtful design.

Would be keen to see anything CoArbitrary-like you come up with

**Comment by bitemyapp** [comment]
@thumphries well, the problem I'm having right now is translating the chip/chop code layered on top of `tf-random` in QuickCheck to what I'd be doing w/ the existing splittable PRNG in Hedgehog. There are some magic values that I am able to sort-of understand with respect to how the code permutes the `TFGen` but I don't feel like I can do a correct implementation of `variant` without talking to someone that understands the original QuickCheck code better. Maybe @nick8325 or @treeowl? I saw them in the `magit-blame` for `Test.QuickCheck.Random`.

It's strange to me you say you don't need this often, cf. https://github.com/bitemyapp/hedgehog-checkers

Are you saying you don't ever validate your typeclass laws? I find myself needing Gens for functions for application properties sometimes too.

**Comment by thumphries** [comment]
> Are you saying you don't ever validate your typeclass laws? I find myself needing Gens for functions for application properties sometimes too.

I just generate functions from a map for that kind of thing right now, same as you. The functions QuickCheck generates are not particularly interesting IME, usually not much more than `const foo`, so it's been close enough

YMMV, we'd all like to see some other perspectives on how that sort of thing might fit into Hedgehog

**Comment by bitemyapp** [comment]
@thumphries you get a lot more variety in terms of mapping arguments to outputs out of QuickCheck's setup. I'm surprised you think they're comparable. Trying to make a `Map` that covers the same gamut of input to output mappings is _extremely_ slow.

**Comment by thumphries** [comment]
Not here to argue with you, it's obviously a naive strategy, post a PR if you have anything better
