### ISSUE TITLE
Please add MonadMask instance to PropertyT

### ISSUE THREAD

**Issue by newhoggy** [hedgehogqa/haskell-hedgehog#182]
This would make it possible to create temporary files within a property test.

```
    • No instance for (exceptions-0.8.3:Control.Monad.Catch.MonadMask
                         (PropertyT IO))
        arising from a use of ‘IO.withSystemTempFile’
```

**Comment by thumphries** [comment]
Haven't attempted to add this but there is an ExceptT in the stack there. Newer versions of `exceptions` have a MonadMask instance for `ExceptT`, but those versions are not yet in popular use, and older versions of the typeclass do not have a valid ExceptT instance. Might be problematic / require CPP

**Comment by newhoggy** [comment]
Thanks!

**Comment by thumphries** [comment]
Let's revisit this in a couple of years when the ExceptT instance is widely deployed.

**Comment by geigerzaehler** [comment]
> Let's revisit this in a couple of years when the ExceptT instance is widely deployed.

Instead of deriving the `MonadMask` instance for the newtype and relying on the instance of `ExceptT` wouldn’t it be possible to write the `MonadMask` instance by hand for `TestT` by hand?

**Comment by kirelagin** [comment]
Is it good time to revisit this now?

**Comment by kirelagin** [comment]
Alright, I went that far, but now I’m stuck:

```haskell
deriving newtype instance MonadMask m => MonadMask (TestT m)
deriving newtype instance MonadMask m => MonadMask (PropertyT m)

instance MonadMask m => MonadMask (GenT m) where
  mask a = GenT $ \size seed ->
    mask $ \u -> runGenT size seed (a $ mapGenT u)

  uninterruptibleMask a = GenT $ \size seed ->
    uninterruptibleMask $ \u -> runGenT size seed (a $ mapGenT u)

  generalBracket acquire release use = GenT $ \size seed ->
    case Seed.split seed of
      (seed1, seed1') -> case Seed.split seed1' of
        (seed2, seed3) -> do
          generalBracket
            (runGenT size seed1 acquire)
            (\treeRes ec -> runGenT size seed2 (release treeRes ec))
            (\treeRes -> runGenT size seed3 (use treeRes))

instance MonadMask m => MonadMask (TreeT m) where
  mask a
    = TreeT $ mask $ \u -> runTreeT (a $ mapTreeT u)

  uninterruptibleMask a
    = TreeT $ uninterruptibleMask $ \u -> runTreeT (a $ mapTreeT u)

  generalBracket acquire release use = {- ??? -}
```

I’m not sure there is a sensible way to make `TreeT` into a `MonadMask` :/.

**Comment by ocharles** [comment]
Is it possible using `control` from `monad-control` and `Control.Exception.mask`?

**Comment by kirelagin** [comment]
I mean, the problem here is in the semantics, and, I suppose, it is the same as with `ListT` (which is not an instance of `MonadMask`). I’m not sure what it means to bracket when the computations for resource acquisition and release have multiple branches.

**Comment by mpickering** [comment]
The suggestion to use `temporary-resourcet` rather than `temporary` doesn't work very well as `temporary-resourcet` does not create unique directory names for different executations within the same process.
