### ISSUE TITLE
Exception thrown when a property is defined in another library

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#188]
We have defined a `PropertyT IO ()` in a separate library to check JSON schemas and when we execute it we get an exception `cannot openFile`. I don't know much about the internals of Hedgehog but I suppose that it is trying to find the source file for the property and is not able to find it.

**Comment by moodmosaic** [comment]
AFAICT, this was addressed by @thumphries in https://github.com/hedgehogqa/haskell-hedgehog/pull/184 and should be available in the next release. /cc @jystic

**Comment by etorreborre** [comment]
Fantastic, I didn't realize it was the same issue. I'm closing then and waiting for the next release.(@jystic when is it due?)

**Comment by jystic** [comment]
@etorreborre I should get to it this week
