### ISSUE TITLE
Deeper QuickCheck comparison write-up

### ISSUE THREAD

**Issue by bitemyapp** [hedgehogqa/haskell-hedgehog#195]
https://www.reddit.com/r/haskell/comments/646k3d/ann_hedgehog_property_testing/dfzth64/

Previous thread's topic was resolved so opening a new one to stay on topic,

>There is a more formal write up in-progress, but nothing useful I can point you to yet I'm afraid.

Did that ever land anywhere?

**Comment by jystic** [comment]
I’m afraid it didn’t, I was working on a paper but I didn’t finish in time for the conference I wanted to submit to and it lost steam after that. I would still like to finish it at some point but I’m really focused on my new job at the moment.

**Comment by bitemyapp** [comment]
Thanks! I'll make the rounds to see if I can assemble a consensus on the ups and downs of each. If you do ever find time for it, please announce it far and wide!
