### ISSUE TITLE
Add properties for Semigroup and Monoid laws

### ISSUE THREAD

**Issue by ChShersh** [hedgehogqa/haskell-hedgehog#199]
There's already nice and useful [`tripping`](http://hackage.haskell.org/package/hedgehog-0.6/docs/Hedgehog-Internal-Tripping.html#v:tripping) combinator.

I think it will be useful to have something like that since it's a very often case for testing (at least I didn't found this combinator in :

```haskell
semigroupAssoc :: (Semigroup a, Eq a, Show a, MonadTest m, HasCallStack) => Gen a -> m ()
semigroupAssoc genSemigroup = do
    x <- forAll genSemigroup
    y <- forAll genSemigroup
    z <- forAll genSemigroup
    (x <> y) <> z === x <> (y <> z)

monoidNeutral :: (Monoid a, Eq a, Show a, MonadTest m, HasCallStack) => Gen a -> m ()
monoidNeutral genMonoid = do
    x <- forAll genMonoid
    x <> mempty === x
    mempty <> x === x
```

(not sure it works and typechecks, just the idea).

Though, `tripping` combinator is implemented in more smart way so maybe implementation for such properties also should be smarter with prettier output...

**Comment by ChShersh** [comment]
@thumphries Thanks! Haven't heard about this package. Will look into this.

**Comment by chessai** [comment]
@ChShersh https://github.com/chessai/hedgehog-classes

**Comment by moodmosaic** [comment]
https://github.com/qfpl/hedgehog-laws

**Comment by chessai** [comment]
@moodmosaic that package seems really incomplete, and hasn't been updated in a while. The same can be said of `hedgehog-checkers`. hedgehog-classes supports the following:

```haskell
  Alternative
, Applicative
, Arrow
, Bifoldable
, Bifunctor
, Bitraversable
, Bits/FiniteBits
, Category
, Contravariant
, Enum
, Eq
, Foldable
, Functor
, Generic
, Integral
, Ix
, FromJSON/ToJSON (partial isomorphism)
, Monad
, MonadIO
, MonadZip
, Monoid
, Ord
, Semigroup
, Show
, ShowRead
, Storable
, Traversable
```

`Hedgehog.Classes.Category` has an additional test for commutative category laws,
`Hedgehog.Classes.Enum` has an additional test for boundedEnumLaws (making sure succ/pred dont' `error`)
`Hedgehog.Classes.Monoid` has an additional test for commutative monoids
`Hedgehog.Classes.Semigroup` has additional tests for commutative semigroups, exponential semigroups, idempotent semigroups, and rectangular band semigroups.

`semigroupoids` tests are to come.

**Comment by moodmosaic** [comment]
@chessai, sweet!

**Comment by ChShersh** [comment]
@chessai This is a huge work! Thanks a lot for working on this :heart: 
@moodmosaic the issue is resolved for me, feel free to close it :+1:
