### ISSUE TITLE
Print re-check information if the source is not found

### ISSUE THREAD

**Issue by peddie** [hedgehogqa/haskell-hedgehog#210]
If I run my hedgehog tests from the wrong directory and they find a failed property, the program immediately dies with an exception from `openFile`.  This is a shame if my tests have been running for a couple hours -- would it be possible to print out the recheck information (size and seed values) no matter what happens with the source rendering?  Then I can just move to the right directory and call `recheck`.

This problem is less bad once I can set the seed manually, but as it stands, hedgehog may find failures I can never replicate.

**Comment by thumphries** [comment]
I think this has been fixed in recent versions - see https://github.com/hedgehogqa/haskell-hedgehog/pull/184.

Feel free to reopen if that is not the case!

**Comment by thumphries** [comment]
Specifically, `hedgehog-0.6` or higher.
