### ISSUE TITLE
commandGen and Require seem to be redundant

### ISSUE THREAD

**Issue by onepunchlinux** [hedgehogqa/haskell-hedgehog#212]
From the documentation: 

commandGen: A generator which provides random arguments for a command. If the command cannot be executed in the current state, it should return Nothing.

Require: A pre-condition for a command that must be verified before the command can be executed. This is mainly used during shrinking to ensure that it is still OK to run a command despite the fact that some previously executed commands may have been removed from the sequence.

Wouldn't you want to express the same precondition before generating a command or shrinking? Can one be used instead of the other?

**Comment by thumphries** [comment]
Closing as resolved, feel free to reopen if you would like to discuss further.
