### ISSUE TITLE
Discovery doesn't see properties defined via pattern matches

### ISSUE THREAD

**Issue by cemerick** [hedgehogqa/haskell-hedgehog#237]
e.g., `discover` doesn't see the two properties defined here:

```hs
(prop_reverse, prop_chr_ord) = ( property $ xs >>= \x -> reverse (reverse x) === x
                               , property $ xs >>= \x -> map chr (map ord x) === x )
  where xs = forAll $ Gen.list (Range.linear 0 100) Gen.alpha
```

The workaround given the current impl of things in `Hedgehog.Internal.Discovery` is to ensure that the property declarations start in the first column:

```hs
exampleProperties = ( property $ xs >>= \x -> reverse (reverse x) === x
                    , property $ xs >>= \x -> map chr (map ord x) === x )
  where xs = forAll $ Gen.list (Range.linear 0 100) Gen.alpha

prop_reverse = fst exampleProperties
prop_chr_ord = snd exampleProperties
```

Supporting tuple matches in `Hedgehog.Internal.Discovery` seems feasible, and I'd be willing to make a patch for that. (Anything more than that — e.g. record field matches or even lists — might be complicated enough to warrant a more significant change to use a proper source parser.)

**Comment by moodmosaic** [comment]
Yeah, I don't think anyone ever used it that way. Perhaps because sometimes [`Group`](http://hackage.haskell.org/package/hedgehog-0.6.1/docs/Hedgehog.html#t:Group) is all you need, since it's really a named collection of property tests:

```haskell
-- | A named collection of property tests.
--
data Group =
  Group {
      groupName :: !GroupName
    , groupProperties :: ![(PropertyName, Property)]
    }
```

If we were adding support for tuple matches, what would happen with triples, quadraples, and so on?

**Comment by cemerick** [comment]
OK, I thought that `prop_` declarations had to be `Property`s. If the advice is "just yield a `Group` for any compound declarations that e.g. share generators not worth making top-level", that's fine by me.

If tuple matches were supported, then yeah, I'd expect any size tuples to be included there. Moving along to an established source parser would simplify handling that and lots of other cases.

**Comment by moodmosaic** [comment]
>If tuple matches were supported, then yeah, I'd expect any size tuples to be included there.

Which might be a bit tricky.

>Moving along to an established source parser would simplify handling that and lots of other cases.

Unless we probably do it this way — which may as well be on a downstream library.

---

Here's another example of grouping properties: https://github.com/hedgehogqa/haskell-hedgehog/blob/1f14eee44cf586c3ba9ef34c219bd5a83c8ede97/hedgehog/test/test.hs#L14-L20

Each module has its own `tests` function:

Test.Hedgehog.Text.tests:
https://github.com/hedgehogqa/haskell-hedgehog/blob/1f14eee44cf586c3ba9ef34c219bd5a83c8ede97/hedgehog/test/Test/Hedgehog/Text.hs#L74-L76
 
https://github.com/hedgehogqa/haskell-hedgehog/blob/1f14eee44cf586c3ba9ef34c219bd5a83c8ede97/hedgehog/test/Test/Hedgehog/Seed.hs#L82-L84

Here's another example, this time with `Group`: https://github.com/hedgehogqa/haskell-hedgehog/pull/173#discussion_r220116453. — You can mix and match all those.

**Comment by thumphries** [comment]
IIRC Jake set out to use a source parser / haskell-lexer initially. It’s not that easy. Things like CPP make it pretty painful (if Hedgehog has to know about Cabal macros something is wrong).

This implementation was the most robust of the ones attempted. It is slightly better than QuickCheck’s, since it handles comments properly, but that’s about all you get.

Would suggest just not using tuple declarations. Too difficult to do otherwise.

**Comment by cemerick** [comment]
@moodmosaic thanks for pointing out the additional workarounds.

@thumphries Appreciate the historical note! FWIW, I wasn't intending to trivialize whatever the challenges are/were in alternative approaches (as might be clear, I'm not familiar with them); the suggestion to maybe use a different approach was strictly of the casual, spitballing sort.

Closing given the workarounds, etc., but ofc feel free to reopen if you decide it's worth keeping afloat.
