### ISSUE TITLE
Integrate with tasty?

### ISSUE THREAD

**Issue by minad** [hedgehogqa/haskell-hedgehog#24]
Is there some interest in integrating that with tasty, i.e., provide a tasty-hedgehog package similar to tasty-quickcheck?

**Comment by dalaing** [comment]
I'm already working on this :)

**Comment by minad** [comment]
great, I also started fiddling with that. Then I will stop :)

It seems to me that hedgehog is tightly coupled with its runner or did you find some functions which make it easy to integrate with the tasty runner?

**Comment by dalaing** [comment]
No need to stop if you don't want to :) It's late here so you'll have a day or so until I try to finish it off. 

I'm using the hedgehog runner, mostly following what was done in tasty-quickcheck. I need to update it to provide progress updates now that they are a thing, after that it should be good to go.

**Comment by minad** [comment]
No hurry for me, I just started like you based on tasty-quickcheck. There is not much I have - see below. So if you have a solution to avoid that tasty console output and hedgehog output conflict, please proceed. In principle I would suggest that we create a github repo to collaborate on that, but this is also a simple thing which is done in a short while. But if you need someone as collaborator/maintainer, I would be happy.

~~~ haskell
module Test.Tasty.Hedgehog (
    testProperty
    , testProperty'
    , module H
) where

import Text.Read (readMaybe)
import Test.Tasty.Providers
import Test.Tasty.Options
import Test.Tasty.Runners (formatMessage)

import Data.Proxy
import Data.List
import Data.Monoid
import Text.Printf
import Control.Applicative
import qualified Hedgehog as H

newtype Hedgehog = Hedgehog H.Property

-- -- | Create a 'Test' for a hedgehog 'H.Testable' property
testProperty :: TestName -> H.Test IO () -> TestTree
testProperty name = singleTest name . Hedgehog . H.property

-- -- | Create a 'Test' for a hedgehog 'H.Testable' property
testProperty' :: TestName -> H.Property -> TestTree
testProperty' name = singleTest name . Hedgehog

newtype HedgehogShrinks  = HedgehogShrinks  (Maybe H.ShrinkLimit)
newtype HedgehogDiscards = HedgehogDiscards (Maybe H.DiscardLimit)
newtype HedgehogTests    = HedgehogTests    (Maybe H.TestLimit)

instance IsOption HedgehogTests where
  defaultValue = HedgehogTests Nothing
  parseValue = fmap (HedgehogTests . Just . fromIntegral) . readMaybe
  optionName = pure "hedgehog-tests"
  optionHelp = pure "Set the number times a property should be executed before it is considered successful."

instance IsOption HedgehogDiscards where
  defaultValue = HedgehogDiscards Nothing
  parseValue = fmap (HedgehogDiscards . Just . fromIntegral) . readMaybe
  optionName = pure "hedgehog-discards"
  optionHelp = pure "Set the number times a property is allowed to discard before the test runner gives up."

instance IsOption HedgehogShrinks where
  defaultValue = HedgehogShrinks Nothing
  parseValue = fmap (HedgehogShrinks . Just . fromIntegral) . readMaybe
  optionName = pure "hedgehog-shrinks"
  optionHelp = pure "Set the number times a property is allowed to shrink before the test runner gives up and prints the counterexample."

instance IsTest Hedgehog where
  testOptions = pure
    [ Option (Proxy :: Proxy HedgehogShrinks)
    , Option (Proxy :: Proxy HedgehogTests)
    , Option (Proxy :: Proxy HedgehogDiscards)
    ]

  run opts (Hedgehog prop) yieldProgress = do
    let HedgehogTests      nTests     = lookupOption opts
        HedgehogDiscards   nDiscards  = lookupOption opts
        HedgehogShrinks    nShrinks   = lookupOption opts
     ...
~~~

**Comment by jystic** [comment]
> It seems to me that hedgehog is tightly coupled with its runner or did you find some functions which make it easy to integrate with the tasty runner?

The best place to hook in would probably be [checkReport](http://hackage.haskell.org/package/hedgehog-0.1/docs/Hedgehog-Internal-Runner.html#v:checkReport), it is marked as an internal function at the moment, but something like that could be made a supported API. As a "nice" supported API it would probably look a little different, but it's probably good enough as is to get you going.

`checkReport` will call the provided callback function before each test and during shrinking to give status updates, and it will produce a [Report](http://hackage.haskell.org/package/hedgehog-0.1/docs/Hedgehog-Internal-Report.html#t:Report) at the end. You can render a `Report` using [renderReport](http://hackage.haskell.org/package/hedgehog-0.1/docs/Hedgehog-Internal-Report.html#v:renderReport).

**Comment by dalaing** [comment]
I've got my version of `tasty-hedgehog` [here](https://github.com/dalaing/tasty-hedgehog).

I still need to clean up the information that it outputs, and integrate the concurrent reporting with the progress reporting capabilities of `tasty`, but it's a start.

**Comment by thumphries** [comment]
This is done - see https://github.com/qfpl/tasty-hedgehog !!!

**Comment by moodmosaic** [comment]
Cool, I've opened https://github.com/feuerbach/tasty/pull/192 to include `tasty-hedgehog` on the list 🚀
