### ISSUE TITLE
Hedgehog tests fail with `Gave up` output when no `discard` combinators are used

### ISSUE THREAD

**Issue by ChShersh** [hedgehogqa/haskell-hedgehog#244]
I've started to observe `Gave up` results in my generator. And I don't even use `discard` at all (relevant discussion: #186)! So this looks quite weird. You can see the generator here:

* https://github.com/kowainik/tomland/blob/03e50301fc985354940326f7bf9796ddf4da9c39/test/Test/Toml/BiCode/Property.hs#L136-L162

What's more interesting, Travis CI jobs somehow pass for GHC-8.2.2 and GHC-8.4.4 but fail for GHC-8.6.3:

* https://travis-ci.org/kowainik/tomland/builds/478288756?utm_source=github_status&utm_medium=notification

I'm quite puzzled by what's going on and can't even debug the issue... I appreciate any help with this :pray:

**Comment by charleso** [comment]
@ChShersh Just a _completely_ random guess after glancing at your code

https://github.com/kowainik/tomland/blob/03e50301fc985354940326f7bf9796ddf4da9c39/test/Test/Toml/BiCode/Property.hs#L202

I'm pretty sure you can't generate a set of booleans greater than size 2, and so [`set -> map -> uniqueByKey`](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/hedgehog/src/Hedgehog/Internal/Gen.hs#L1358) will _always_ `discard` if it generates the size of the set to be > 2. 

If in doubt I would suggest adding hedgehog as a source dependency via your build tool and add some tracing to discard to work out where/who is calling it.

Good luck.

**Comment by ChShersh** [comment]
@charleso Are, indeed! Thanks, that resolves my issue!
