### ISSUE TITLE
Generation of special values

### ISSUE THREAD

**Issue by minad** [hedgehogqa/haskell-hedgehog#25]
Using quickcheck I had the problem that it doesnt generate special values or edge cases. Therefore I made a newtype wrapper which provides appropriate arbitrary instances. See https://github.com/minad/quickcheck-special

Maybe something like this could be integrated in hedgehog out of the box?

**Comment by jystic** [comment]
Yeah that certainly seems like a good idea, it has a bit in common with [disorder-corpus](https://github.com/ambiata/disorder.hs/blob/master/disorder-corpus/src/Disorder/Corpus.hs#L384) which provides collections of related text for testing purposes.

**Comment by minad** [comment]
cool! Sth like that should be integrated. I needed especially the NaN values, but these international texts seem to be a great addition too. Compared to QC it should be possible to integrate this nicely due to how hedgehog generates values, I think!

**Comment by thumphries** [comment]
[hedgehog-corpus](https://hackage.haskell.org/package/hedgehog-corpus) is now on Hackage for generating text. These don't provide many edge cases, but Hedgehog's core combinators do, so it is easy to write generators that shrink towards plain English with `Gen.choice`.

Hedgehog doesn't really have a way to generate `NaN` out of the box at the moment; I've been writing things like

```haskell
genDouble :: Gen Double
genDouble =
  Gen.frequency [
      (90, Gen.double {- etc -})
    , (5, pure (0/0)) -- nan
    , (5, pure (1/0)) -- inf
    ]
```

which does the job well enough
