### ISSUE TITLE
Please expose Hedgehog.Internal.Report.TestCount constructor

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#26]
I'm currently adding a Hspec wrapper to Hedgehog so that Hedgehog can be used with Hspec.

To do that I need access to some of the internals, but unfortunately, the `TestCount` newtype can only be pretty printed because the constructor is not exported.

**Comment by minad** [comment]
I don't understand the purpose if hiding the newtypes but still you could use fromIntegral to extract the values, right?

**Comment by minad** [comment]
Having said that, I would prefer if the newtypes would be exposed and wouldn't newtype derive all the functions:

~~~ haskell
newtype TestCount =
  TestCount Int
  deriving (Eq, Ord, Show) -- no Num, Enum, Real, Integral
~~~

While I think newtype wrappers are useful here, I don't see TestCount etc as a new Num type which should have that instance. Thoughts?

**Comment by erikd** [comment]
> I don't understand the purpose of hiding the newtypes but still you could use fromIntegral to extract the values, right?

Ah yes, I missed that `TestCount` derivied the ``Integral` type class and hence provides `fromIntegral`. Neat!

**Comment by jystic** [comment]
I guess I intended them to just be numbers, in hedgehog I use them as numbers (e.g. `tests + 1`, `0`, etc)

**Comment by jystic** [comment]
I've updated the docs to explain how this works so it's a big more obvious.
