### ISSUE TITLE
Add recheck command to README

### ISSUE THREAD

**Issue by FintanH** [hedgehogqa/haskell-hedgehog#265]
I'm not sure how to run the recheck with the seed, it would be really useful info to have in the README :)

**Comment by moodmosaic** [comment]
All the public and internal API is documented on hackage. Perhaps more haddock comments is what we need?

I just don't think that the README.md is the best place for things like this.

Perhaps some separate tutorial markdown file would be best.

**Comment by FintanH** [comment]
Usage tutorials are always great! :)

I'm curious as to why you think it shouldn't go in the README since it already has the minimal example for getting up and running? I think adding what to do upon failure isn't the biggest stretch, but you know better :)

**Comment by jystic** [comment]
We do already print the usage instructions for `recheck` after every test failure:
```
    This failure can be reproduced by running:
    > recheck (Size 1) (Seed 6043815965182080260 5082204861531945465) <property>
```

**Comment by FintanH** [comment]
Good point, I initially didn't pick up on that :sweat_smile: _Maybe_ the message could be added to saying that `recheck` can be found in the `Hedgehog` module or something like that? Just making it _super_ obvious for someone like me :smile: But really I think the tutorial suggestion would be the best way to go :ok_hand: I'll close this, thanks for all the help @moodmosaic @jystic :100:
