### ISSUE TITLE
Test case generation fails, returns constant value

### ISSUE THREAD

**Issue by cjenn** [hedgehogqa/haskell-hedgehog#266]
This example test:
```haskell
{-# language TemplateHaskell #-}

import Hedgehog
import qualified Hedgehog.Gen as Gen
import qualified Hedgehog.Range as Range

import Control.Monad (guard)

float = Gen.float (Range.linearFracFrom 0 1000 1000)

prop_notEq = property $ do
    x <- forAll float
    y <- forAll float
    guard (x /= y)
    x /== y

main :: IO ()
main = checkSequential $$(discover) >> return ()
```

Gives us this output:
```
━━━ Main ━━━
  ⚐ prop_notEq gave up after 100 discards, passed 0 tests.
  ⚐ 1 gave up.
```

if you put some debug code inside there, you can see that the generator
is just repeating `1000` over and over, as if it was a constant range.

This error occurs with ghc 8.6.4, and you should be able to reproduce it by
just creating an empty stack project (I checked this on lts-13.16) and putting the
example file in test/Spec.hs.

**Comment by HuwCampbell** [comment]
Your upper and lower bounds are both 1000 in the `Range.linearFracFrom 0 1000 1000`, which is why this is constantly returning 1000.

You can check this with
```haskell
bounds   0 $ Range.linearFracFrom 0 1000 1000
bounds 100 $ Range.linearFracFrom 0 1000 1000
```

You probably want something more like `Range.linearFracFrom 0 0 1000`.

**Comment by cjenn** [comment]
wow.

I really shouldn't stay up programming until 4 am.
