### ISSUE TITLE
Stateful generation

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#287]
I would like to implement something like `cycle`
```
cycle :: [Gen a] -> Gen a
```
So that each time we generate a value `a` we use a different generator in the original list in a deterministic fashion, one after the other. 

I tried to implement this with something like `GenT (StateT s) a` but couldn't make it work.

Similarly with some stateful generation we could implement something like `distinct :: Gen a -> Gen a` which would keep a list of already generated values and only generate new ones.

Is this possible?

**Comment by jacobstanley** [comment]
Neat ideas! I will have something for you soon.

**Comment by jacobstanley** [comment]
Note that I think this is only really possible within a test, not across all tests for a property unless you get something like `IORef` involved.

**Comment by etorreborre** [comment]
I got something working and it is indeed scoped to a test which I think is what we want: https://medium.com/@etorreborre_99063/scrap-your-typeclasses-take-2-32ce9fb18810

**Comment by jacobstanley** [comment]
I managed to get `cycle` to work without `IO` but I couldn't make a workable `distinct`

**Comment by etorreborre** [comment]
That's already great! Do you have a branch for that?

**Comment by jacobstanley** [comment]
This is the branch I'm working on (https://github.com/hedgehogqa/haskell-hedgehog/compare/master...jacobstanley:topic/state-t), but I'm not sure if it will get there in the end, I think I'm relying on something which is unsound to implement `MonadTransDistribute` for `StateT` which is required to get a reasonable type signature for cycle.

**Comment by jacobstanley** [comment]
Note that I had to remove the `MonadGen` instance for `StateT` in the 1.0 release because I couldn't figure out how to implement it with the new `MonadGen` `toGenT` / `fromGenT` requirements. You can still use `StateT` on the inside of a `GenT` however and use `distributeT` to bring it to the outside and run it.

The branch I'm working on tries to implement `MonadTransDistribute` for `StateT` without having a `MonadTransControl` constraint (which is what makes it impossible to use with `GenT` / `TreeT`)

**Comment by etorreborre** [comment]
Great, I will follow those developments, I find it interesting that you are working around `StateT` by using `Reader (Writer Last)`, I never saw that before.

I had a small question, about those 2 constraints being redundant:
 - https://github.com/hedgehogqa/haskell-hedgehog/compare/master...jacobstanley:topic/state-t#diff-29063d84689b7041a95541e130427d89R7
- https://github.com/hedgehogqa/haskell-hedgehog/compare/master...jacobstanley:topic/state-t#diff-29063d84689b7041a95541e130427d89R98

In the sense that `Reader s (Writer (Last s))` gives you `Writer (Last s)` as well. 
But this is just a matter of being convenient without restricting anything in terms of implementation.

**Comment by jacobstanley** [comment]
> Great, I will follow those developments, I find it interesting that you are working around `StateT` by using `Reader (Writer Last)`, I never saw that before.

I think it's not sound / shouldn't work, but for some reason seems to work in this situation :grimacing:  I'm not sure it will work out.

Those diffs didn't seem to work?

**Comment by etorreborre** [comment]
Darn, the diffs were pointing out those constraints
```
  Monad (f (Lazy.WriterT (Last s) m))
, Monad (f (ReaderT s (Lazy.WriterT (Last s) m)))
```
Where one should imply the other, but having both is just convenient.

**Comment by jacobstanley** [comment]
> Where one should imply the other, but having both is just convenient.

yeah the key word there is _should_, ghc's constraint solver isn't that smart unfortunately

**Comment by etorreborre** [comment]
@jacobstanley quite possibly my needs for `cycle` are actually better covered by integrating enumerative testing with Hedgehog: #305

**Comment by jacobstanley** [comment]
Cool!

**Comment by symbiont-sam-halliday** [comment]
I was also interested in this and since I couldn't get `GenT State` to work I tried `StateT Gen` instead. This is what I came up with as a general pattern, but it'd be far better to have it work with `GenT State` so the `evalStateT` doesn't need to be "inside" the `forAll`

```haskell
module StateTest where

import Control.Applicative (liftA2)
import Control.Monad.State
import Hedgehog
import qualified Hedgehog.Gen as Gen
import qualified Hedgehog.Range as Range
import Prelude

type G a = StateT [Int] Gen a

-- a stateful list generator. If the state is empty it will create a new list,
-- otherwise it will repeat the state. Therefore all lists in the same node of
-- the shrink tree should be the same.
genList :: G [Int]
genList = do
  let domain :: Gen Int = Gen.int (Range.linear 0 100)
      create :: Gen [Int] = Gen.list (Range.linear 1 10) domain
  st <- get
  case st of
    [] -> do
      new <- lift create
      put new
      pure $ new
    other -> pure other

hprop_badstate :: Property
hprop_badstate =
  property $ do
    (xs, ys) <- forAll . (flip evalStateT) mempty $ liftA2 (,) genList genList
    liftIO $ putStrLn (show (xs ++ ys))
    (reverse xs) ++ (reverse ys) === xs ++ ys
-- this should fail, we're interested in the shrinks
```

**Comment by sshine** [comment]
I posted [Running a stateful Hedgehog generator](https://stackoverflow.com/questions/58128625/running-a-stateful-hedgehog-generator) on StackOverflow before finding this message thread.

@jacobstanley wrote:

> Note that I had to remove the `MonadGen` instance for `StateT` in the 1.0 release because I couldn't figure out how to implement it with the new `MonadGen` `toGenT` / `fromGenT` requirements. You can still use `StateT` on the inside of a `GenT` however and use `distributeT` to bring it to the outside and run it.

Can I make this `distributeT` trick apply to my example below?

```haskell
genTree1 :: (MonadGen m, MonadState Int m) => m (Tree String)
genTree1 =
  Gen.recursive Gen.choice
    [ (`Node` []) <$> next ]
    [ Node <$> next <*> Gen.list (Range.linear 0 20) genTree1 ]
  where
    next :: MonadState Int m => m String
    next = fmap show (get <* modify (+1))
```

**Comment by symbiont-sam-halliday** [comment]
> remove the `MonadGen` instance for `StateT` in the 1.0 release

:disappointed: well that explains everything. This means that even simple generators like `Gen.list` can't be used with state. I really hope that this problem can be fixed: the ability to write stateful generators was one of the things that interested me in hedgehog.
