### ISSUE TITLE
Release hedgehog-quickcheck

### ISSUE THREAD

**Issue by kim** [hedgehogqa/haskell-hedgehog#296]
Version `0.1` as released on Hackage has an upper bound for `hedgehog < 1.1`. However, it doesn't build with `1.0` due to its use of `lift`/`liftGen`.

Since this is already fixed here, could you upload a new version?

Thanks!

**Comment by jacobstanley** [comment]
Oh of course, sorry about that, will do

**Comment by jacobstanley** [comment]
`hedgehog-quickcheck-0.1.1` is released.

Please re-open if there's any further issues :fire:
