### ISSUE TITLE
Consider splitting the Status type

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#30]
At the moment, the [Status](http://hackage.haskell.org/package/hedgehog-0.1/docs/Hedgehog-Internal-Report.html#t:Status) type has some constructors like `Running` and `Shrinking` that should only occur when the test is running and other status constructors like `Ok`, `GaveUp` and `Failed` which should only occur when a test is complete.

It would be nice to split these up so that `Waiting`, `Running` and `Shrinking` are part of a `RunningStatus` while `Failed`, `GaveUp` and `Ok` are part of a `ResultStatus`.

**Comment by erikd** [comment]
This would allow a `Report` type that only allowed `RunningStatus` and a `Result` type that only allowed a `ResultStatus` so that `checkReport` could have type:
```
checkReport ::
     forall m.
     MonadIO m
  => MonadCatch m
  => PropertyConfig
  -> Size
  -> Seed
  -> Test m ()
  -> (Report -> m ())
  -> m Result
```

**Comment by jystic** [comment]
Yeah this seems reasonable, I'll have a think about the cleanest way to do this

**Comment by jystic** [comment]
Sorry, I'm going to be pendantic about how this works, so I'd rather do it myself if that's cool 😄 

I'll take a look tonight though if you like?

**Comment by erikd** [comment]
If you look at it tonight you'll get to it way before me :).
