### ISSUE TITLE
filterMaybeT from Hedgehog.Internal.Tree broken

### ISSUE THREAD

**Issue by ruhatch** [hedgehogqa/haskell-hedgehog#301]
I don't have an easy set of steps to repro this, as it's occurred on a local branch of input-output-hk/cardano-ledger-specs, but I ran into an issue where `runDiscardEffect` was throwing `fromJust: Nothing`.

I hunted this down to `filterMaybeT` in `Hedgehog.Internal.Tree` and found that replacing that with `filterT` from further down in the module fixed the error. From a quick look this could be due to a missing `p x` check on the root of the `Tree` in `filterMaybeT`.

I managed to find a workaround by using `runDiscardEffectT` instead, hence not providing a fix for this. I believe a careful review of that function, and some tests, should hopefully solve this problem.

**Comment by jacobstanley** [comment]
Thanks for the report, we definitely want to get on to this one. Maybe it's about time Hedgehog itself grew some more tests, it's a bit like the mechanics car at the moment.

**Comment by treeowl** [comment]
A good start would be to purge the codebase of `fromJust` calls, preferring `mapMaybe` and `traverseMaybe`-like functions to `filter`-like ones. I don't really understand what's going on in `filter` and such well enough to do this properly.  By the way: the special behavior of `Tree.filter` at the root of the tree feels very weird, at least out of context. What's the logic behind it?

**Comment by treeowl** [comment]
It looks to me as though the documentation of `filterMaybeT` doesn't match its (incomplete) documentation. In particular, it never applies the predicate to the root of the tree.

**Comment by treeowl** [comment]
Aside from helping avoid internal partial functions, functions like `mapMaybe` and `traverseMaybe` have the wonderful property of producing type errors when you forget to apply the user-passed function.
