### ISSUE TITLE
Why is distributive instance for StateT so complicated?

### ISSUE THREAD

**Issue by tomjaguarpaw** [hedgehogqa/haskell-hedgehog#316]
I've become interested in the notion of distributive `MFunctor`s.  I was wondering why [`hedgehog`s implementation of `distributeT` for `StateT`](https://github.com/hedgehogqa/haskell-hedgehog/blob/ff11493e49b89749025e0694ad890454c306fa14/hedgehog/src/Hedgehog/Internal/Distributive.hs#L82) is so complicated (involving `MonadTransControl` and `MonadTransJuggle`).  [I have an implementation](https://www.reddit.com/r/haskell/comments/cualvg/does_this_monadcommute_exist/) that seems much closer to `hedgehog`s implementations for `MaybeT`, `WriterT`, `ExceptT` and `ReaderT`.  Is my version incorrect?  Does `hedgehog`'s version have some benefit, perhaps terms of performance?  If it does then it would be good to explain that in the documentation.

**Comment by jacobstanley** [comment]
I suspect the answer is just that I wasn't smart enough to make it simpler. :laughing: 

I would love a different implementation of this! I'm pretty sure my version is not even correct. I've sunk more hours than I can count in to distribute for StateT and I'm really not very happy with it.

**Comment by tomjaguarpaw** [comment]
Well, feel free to steal mine!

**Comment by tomjaguarpaw** [comment]
(assuming mine is valid)

**Comment by HuwCampbell** [comment]
I built a branch expanding on your definitions which seemed to work quite well.

**Comment by HuwCampbell** [comment]
https://github.com/hedgehogqa/haskell-hedgehog/compare/master...HuwCampbell:topic/distribute-simple?expand=1

**Comment by tomjaguarpaw** [comment]
Fantastic!  It looks a lot simpler.

**Comment by jacobstanley** [comment]
Nice @HuwCampbell this looks great! So simple.

I don't know how we go about testing it, but seems like one of those things that if it type checks is probably right. Really if state machine shrinking looks like it works then it's probably fine. I'd be surprised if this is a heavily used feature outside of that.

I've been suspicious that my (complex) implementation may have introduced some bugs in the state machine testing for v1. Would be interesting to see if this fixes it.

The issue I have seen which I never saw prior to 1.0 was post-shrinking some state machine vars were "out of order". Like the variable id they were assigned was not monotonically increasing.

**Comment by HuwCampbell** [comment]
Yeah I was wondering about how to test it as well; but potentially fixing a bug while making it cleaner sounds pretty good to me.

You've probably a few big state machine tests on internal projects. Do you want to hit some with it?
You can then cherry pick this commit in or I can put up a PR.

**Comment by jacobstanley** [comment]
Thanks @tomjaguarpaw and @HuwCampbell I've merged the simplified version!
