### ISSUE TITLE
Allow ansi-terminal-0.10 on Hackage

### ISSUE THREAD

**Issue by mpilgrem** [hedgehogqa/haskell-hedgehog#326]
On the master branch, the recent commit that created the `hedgehog-1.0.1` `.cabal` file (see https://github.com/hedgehogqa/haskell-hedgehog/commit/d893c1a5ff7d2c7d1fed108415e7c3d4417ed446 and #324) included the prior bump to increase the upper bound on `ansi-terminal` (see #322) but the package description actually released to Hackage does not reflect the change to the upper bound.

Could the package description on Hackage be revised to increase the upper bound for `ansi-terminal`?

(A need for the bump is here: https://github.com/kowainik/co-log/pull/147.)

**Comment by moodmosaic** [comment]
Sorry about that. Perhaps I forgot to pull from `master` after merging #322. Need to fully automate   source distributions :eyes: /cc @jacobstanley 

The new revision has been published. It will be available to you as soon as you update your package index (e.g. `cabal update`).
