### ISSUE TITLE
option to not format the Show output

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [hedgehogqa/haskell-hedgehog#331]
I'd like to not format the output from `Show` as it doesn't seem to work very well with my generated data. Is there a way to disable this and just use the version that GHC dumps out?

**Comment by jacobstanley** [comment]
Is this for `forAll` ?

In that case you can use [forAllWith](hhttps://github.com/hedgehogqa/haskell-hedgehog/blob/7516d04673563455a55cf69eb1c490fbbb7f2a5f/hedgehog/src/Hedgehog/Internal/Property.hs#L675-L683) instead which takes a rendering function, which could just be `show`.

```haskell
forAllWith :: (Monad m, HasCallStack) => (a -> String) -> Gen a -> PropertyT m a
```
