### ISSUE TITLE
Does it make sense to have a Gen for ()?

### ISSUE THREAD

**Issue by newhoggy** [hedgehogqa/haskell-hedgehog#34]

**Comment by jystic** [comment]
As in `Gen.unit :: Gen ()` ?

Perhaps for consistency? but the implementation can only be `pure ()` I suppose?

**Comment by newhoggy** [comment]
That works.

I had been using:

    unit :: Monad m => Gen.Gen m ()
    unit = Gen.enumBounded

But `pure ()` is better.

I wrote a semigroup property test for pedagogical purposes.  😁

**Comment by chris-martin** [comment]
I also found myself needing this and didn't realize it could be done with pure. Suggested #36 as a documentation fix.

**Comment by jystic** [comment]
@newhoggy are you ok to close out this issue with the addition of the new `Gen.constant` combinator?

**Comment by newhoggy** [comment]
`pure` works for me.  Thanks!
