### ISSUE TITLE
Edge case with the use of the Pretty library

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#355]
`Pretty` tries to display nicely values and even infer if they might represent arithmetic expressions. Unfortunately for some data types, this is bypassing the `Show` instance in a weird way. Here is an example
```
newtype Identifier = Identifier Int deriving (Eq, Ord, Num)

instance Show Identifier where
  show (Identifier n) = "id-" <> show n
```
When I generate Identifiers based only on positive ints I would get: `id (-1)`, `id (-123)`, `id (-92434)`. Where do those negative numbers come from? It turns out that `Pretty` is parsing the numbers in `id-1`, `id-123`, `id-92434`!

I don't really know how to fix this issue, maybe we should remove the pretty-printing of individual values altogether and leave it to the `Show` instance to do its job. Or provide a `PrettyGen` type class to override the default `Pretty` behaviour.

As a temporary workaround, in case this becomes a problem for someone else, I'm playing with Unicode and using an alternative "minus sign": `−` (that's `U+2212`). Then `Pretty` does something slightly less annoying: `id − 1`, `id − 123`, `id − 92434`.

**Comment by HuwCampbell** [comment]
The issue is that `Pretty` assumes lawful `Show` instances, and lexes them with Haskell comparible 98 lexer.

`id-2` is not a single token to a Haskell lexer, so `pretty-show` is doing the best it can.

**Comment by symbiont-eric-torreborre** [comment]
> lawful Show instances

A lawful `Show` instance is supposed to compatible with the Haskell lexer? That's new to me, do you have some reference for that? If that is the case, is there a work-around you can think of?

**Comment by HuwCampbell** [comment]
Here's what the `Show` class says of its derived instances:

> The result of show is a syntactically correct Haskell expression containing only constants, given the fixity declarations in force at the point where the type is declared. It contains only the constructor names defined in the data type, parentheses, and spaces. When labelled constructor fields are used, braces, commas, field names, and equal signs are also used.

So `Show` almost always produces syntactically valid expressions, which is the assumption libraries like `pretty-show` use to operate. User defined instances of course don't *have* to, but it's good practice.

As a work around, just use the derived `Show` instance. Your identifier will still be very readable. If you need a difference rendering for different applications, you could use a `Pretty` instance from a pretty printing library or a custom render function.

**Comment by jacobstanley** [comment]
Yeah the gist is you should be able to paste the result of `Show` in to your code and construct the value. This is why when you show a `Data.Map` the instance produces `fromList [..etc`

I have been thinking about this recently, it's annoying that `pretty-show` doesn't understand quasi-quotes as that would be quite a good way to deal with complex types like ISO8601 time for example.

At work I have a `newtype` which prints as `"[time|2000-01-01T10:00:00|]"` and you then you need to strip the string quotes off to actually use the value in code. Would be nicer if we could do quasi-quotes in the pretty reader.

I have also seen `pretty-simple` which looks like an alternative that can handle misbehaving `Show` instances, but not sure if that should be encouraged.

**Comment by jacobstanley** [comment]
Is there a reason you need to use `Show` like this instead of having say a `renderIdentifier :: Identifier -> String` function?

**Comment by etorreborre** [comment]
Thanks @HuwCampbell and @jacobstanley. After sleeping on it, I realize that I have been indeed abusing `Show`. I should just let it be derived and add a `render` function where I need it.

**Comment by symbiont-sam-halliday** [comment]
Related https://github.com/hedgehogqa/haskell-hedgehog/issues/331
