### ISSUE TITLE
Add evalMaybeM :: MonadTest m => m (Maybe a) -> m a

### ISSUE THREAD

**Issue by ocharles** [hedgehogqa/haskell-hedgehog#368]
As the issue title says, I suggest we add this. I would also suggest `evalMaybe` and `evalEitherM`. I generally use pattern matching for these, but then I don't get nice highlighting :cry:

**Comment by jacobstanley** [comment]
So this would just fail on `Nothing` and point to the correct line?

**Comment by ocharles** [comment]
Yep, you got it!

**Comment by EarthCitizen** [comment]
I was getting ready to open an issue to request `evalMaybe` and found this. +1
