### ISSUE TITLE
Why does Gen.list take a Range Int rather than an Int?

### ISSUE THREAD

**Issue by tomjaguarpaw** [hedgehogqa/haskell-hedgehog#369]
If I want to generate a list with length in a particular range I do `Gen.list range element`. It seems rather awkward to me that `Gen.list` takes a `Range Int` rather than just an `Int`.  Alternatively I could do the following.

```haskell
mylist :: MonadGen m => Int -> m a -> m [a]
mylist n element = Gen.list (Range.singleton n) element

do
  n <- Range.int range
  mylist n element
```

Would that make the testing process worse somehow?  It certainly feels much more natural to me.

**Comment by ocharles** [comment]
If `Gen.list` only took an int, it wouldn't be possible to configure how it varies in size as the size parameter increases. The `Range` DSL gives us the ability to do things like have lists become exponentially larger as the size increases, or maybe even _decrease_ the lower bound as the size increases.

For example, `Gen.list (Range.linearFrom 5 1 100)` means for small sizes we generate lists with approximately 5 elements, but as the size increases, we generate lists with between 1 and 100 elements.

Have you watched "Gens and Roses"? https://www.youtube.com/watch?v=AIv_9T0xKEo 20:35 on describes the range DSL.

**Comment by tomjaguarpaw** [comment]
But doesn't passing the result of `Range.int range` into `mylist` have the same effect?  That is,

```haskell
do
  n <- Range.int range
  mylist n element
```

?

Thanks for the reference to the video.  I will have a look.

**Comment by tomjaguarpaw** [comment]
I realise that the list generator has to be able to vary the size of the generated list, but I don't understand why this must be done via a `Range Int` passed to `list` itself, rather than an `Int` created with `Range.int` in a previous `GenT` action.

**Comment by mitchellwrosen** [comment]
@tomjaguarpaw FYI, I'd be cautious of this monadic style of random generation - it makes shrinking worse.

**Comment by tomjaguarpaw** [comment]
Ah, very interesting.  Worse in what sense?  How can I find out more about that?

**Comment by mitchellwrosen** [comment]
```haskell
do
  n <- Range.int range
  mylist n element
```

Worse in the sense that once `n` is selected, if a counterexample is found, you can't go back and shrink it, so you may end up with a non-minimal test case (i.e. maybe the list is longer than it needs to be).

You can read a lot more about integrated shrinking here https://www.well-typed.com/blog/2019/05/integrated-shrinking/

Hedgehog's `Gen.list` actually doesn't suffer from this problem, but it uses internal types in a kind of complicated way.

**Comment by tomjaguarpaw** [comment]
> Worse in the sense that once n is selected, if a counterexample is found, you can't go back and shrink it

Interesting.  That is very counterintuitive.  I will have to go through the resources that you and @ocharles have suggested.  Thanks both!

**Comment by ocharles** [comment]
Maybe https://www.well-typed.com/blog/2019/05/integrated-shrinking/ will help
