### ISSUE TITLE
Add monadic tripping

### ISSUE THREAD

**Issue by ersran9** [hedgehogqa/haskell-hedgehog#373]
We wanted to use `tripping` for sending a query across network and compare the results. But without `m` in forward and backward directions we were not able to do `IO`. We have an implementation at https://github.com/byteally/haskell-hedgehog/commit/6142fce8a2838bbe1abbe740be2656e883a6467d which adds `trippingM`. I'll be happy to send a PR if its okay.

**Comment by jacobstanley** [comment]
Yeah that's a good, happy to take a PR :tada:

**Comment by ersran9** [comment]
PR #374. Thanks - hedgehog rocks!
