### ISSUE TITLE
The default formatter seems to swallow this exception

### ISSUE THREAD

**Issue by mitchellwrosen** [hedgehogqa/haskell-hedgehog#379]
It's there in the `FailureReport`'s `failureMessage`, but ultimately doesn't make it to the screen. :(

<img width="1230" alt="Screen Shot 2020-04-30 at 5 46 17 PM" src="https://user-images.githubusercontent.com/1074598/80762424-870e0c00-8b0a-11ea-937b-8cb02bc8b6b0.png">

**Comment by adamwespiser** [comment]
Bump

**Comment by adamwespiser** [comment]
Bump

**Comment by HuwCampbell** [comment]
I think I know what's causing this; will look into it.

**Comment by HuwCampbell** [comment]
<img width="830" alt="Screen Shot 2020-06-14 at 5 01 23 pm" src="https://user-images.githubusercontent.com/5205457/84587261-e9c02a80-ae60-11ea-9d86-03ce240c8f53.png">

This seems better, I'll put up a PR.
