### ISSUE TITLE
Need a way to label state machine tests

### ISSUE THREAD

**Issue by ocharles** [hedgehogqa/haskell-hedgehog#401]
From what I can see, we don't have a way to label or do coverage for state machine tests. Once we generate sequential actions, we just get a list of `Action`, but this is entirely opaque. Maybe `Command` should gain a label field, and this should be copied into `Action` as `actionLabel`?

If the maintainers of Hedgehog agree, I'll prepare a pull request.

**Comment by ocharles** [comment]
Ah, I guess this is really the purpose of `Input`. Right now I'm using some reusable combinators, but if each command has its own `Input`, I can pattern match on `actionInput`. `actionInput` is internal though, so if we want to do this, we should add that to the public API.

**Comment by ocharles** [comment]
Sorry, more thinking out loud. `actionInput` isn't much use, because it's existential - I can't really _do_ anything with it, other than `Show` it - but that's far too big for a label (though `head . words` would at least "work" for now).

**Comment by HuwCampbell** [comment]
You can use the standard `label`, `cover`, and `classify` functions inside the `commandExecute` record of commands (you can also put it in an `Ensure` callback).

You just need a `MonadTest` and `MonadIO` constraint.

**Comment by HuwCampbell** [comment]
```haskell
register :: (MonadGen n, MonadIO m, MonadTest m) => Command n m State
register =
  let
    gen s =
      case Set.toList (statePids s) of
        [] ->
          Nothing
        xs ->
          Just $
            Register
              <$> genName
              <*> Gen.element xs

    execute (Register name pid) = do
      cover 90 "register" True
      liftIO $ ioRegister name (concrete pid)
  in
    Command gen execute [
        Require $ \s (Register name _) ->
          Map.notMember name (stateRegs s)

      , Require $ \s (Register _ pid) ->
          notElem pid $ Map.elems (stateRegs s)

      , Update $ \s (Register name pid) _o ->
          s {
            stateRegs =
              Map.insert name pid (stateRegs s)
          }
      ]
```

**Comment by ocharles** [comment]
But that will only work _if_ a command gets executed. It won't fail the test if the command is never executed, because the `cover` will never be reached.

**Comment by HuwCampbell** [comment]
No that's not right. Not mentioned counts as not covered, and the monoid for coverage acts like `Any` from `Data.Monoid`.

If the case isn't hit, it'll count as not being performed in a particular test.

**Comment by ocharles** [comment]
Ok, I don't quite understand - how does Hedgehog even know there's a label called "register" (in your example), if that `execute` is never called (for example, the precondition is never met). Would you need another call before you run state machine tests to add all possible labels?

**Comment by HuwCampbell** [comment]
If a label is never ever called, it won't know about it and the coverage test won't work.

If it gets called once in the set of runs, it'll know about it and can perform a reasonable coverage test.

**Comment by ocharles** [comment]
Ok, so `cover 1 "rare but possible"` might never fail a test if this rare command is never, due our random command selection never being fortunate enough to hit it. That's the case I'm trying to solve - I want a test failure then.

That said, it sounds like my best option is:

* For every `Command`, pre-register a label for this command with `cover` before running any tests.
* For every `Command`, `classify` it according to the same label in `execute`.

If that's true, then I can close this issue as "already works"!

**Comment by ocharles** [comment]
To answer my own question, yes, that's the correct way to do this. Closing! Thanks for the help, @HuwCampbell !
