### ISSUE TITLE
Replace HTraversable with Data.Functor.Barbie.TraversableB

### ISSUE THREAD

**Issue by ocharles** [hedgehogqa/haskell-hedgehog#403]
While I've never been particularly excited about the names in the `barbies` library, it's still an excellent library. A benefit of using their `TraversableB` class (which is our `HTraversable`) is that it has a generic definition, so most things can be:

```haskell
data CommandInput f = CommandInput { foo, bar :: Var Int f }
  deriving (Generic, FunctorB, TraversableB)
```

and it *just works*. This is a pretty huge productivity boon!

**Comment by ocharles** [comment]
Do the maintainers have any thoughts on this? I'm still interested in this

**Comment by jacobstanley** [comment]
I don't mind moving to a standard thing.

I think there are a few options, I remember looking at [rank2classes](https://hackage.haskell.org/package/rank2classes-1.4.1/docs/Rank2.html#t:Traversable) at one point, I think that's also the same.

I think there may even have been another package too but I can't quite remember the name.

**Comment by ocharles** [comment]
My main desire with a move to `barbies` specifically is due to its ability to work with `DeriveAnyClass`. If others can do that - great! But that's the feature I'm really looking for. We could of course roll that ourselves, but it seems easier to just shift this work to any other existing library.

**Comment by jacobstanley** [comment]
Looking through the slack history it was `barbies` that was the "other" library haha

@HuwCampbell had a branch at one point as an experiment, we could bring that up to date:
https://github.com/hedgehogqa/haskell-hedgehog/compare/master...HuwCampbell:topic/barbies?expand=1

**Comment by ocharles** [comment]
It sounds like you're generally in favor of this idea, so I'll take that branch (or start a fresh one) and try and use `barbies`. Hopefully get a PR soon!
