### ISSUE TITLE
Support for GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [hedgehogqa/haskell-hedgehog#416]
Building with `--allow-newer` currently results in a build failure. This patch should help: https://gitlab.haskell.org/ghc/head.hackage/-/blob/ea1b6b35e46870fea5a9596fcac8df0b9cd105bd/patches/hedgehog-1.0.4.patch

**Comment by amesgen** [comment]
It builds fine on master with GHC 9.0.1, I think it only needs a release.

**Comment by moodmosaic** [comment]
Yep, planning for a release this week.

**Comment by moodmosaic** [comment]
@sjakobi, thank you for opening this! Should we close this in favor of https://github.com/hedgehogqa/haskell-hedgehog/pull/392?

**Comment by sjakobi** [comment]
@moodmosaic Feel free to close. I'd love to get a ping once you've uploaded a compatible release though! :)

**Comment by moodmosaic** [comment]
Sure! Let's close it once the release is out, hopefully this week.

**Comment by moodmosaic** [comment]
@sjakobi, we'll do the release once we merge #414 and #415 by @HuwCampbell. Hope that's not blocking you. If it does, please let us know.

**Comment by HuwCampbell** [comment]
I'll fix these up today.

**Comment by vrom911** [comment]
Thanks a lot for working on this, everyone! 

@moodmosaic seems like both of the mentioned PRs are merged now. Do you have any estimates on the releasing? And do you probably need any extra help in order to speed up this one? 🙂

**Comment by moodmosaic** [comment]
Unfortunately I got sick 😥 so it might take a few days more, unless @jacobstanley can do it today or tomorrow.

**Comment by sjakobi** [comment]
Get well soon, @moodmosaic! :) FWIW, my need for a compatible hedgehog release is not particularly urgent.

**Comment by vrom911** [comment]
Get well soon, @moodmosaic ! No worries, this could, of course, wait. Take care of yourself first 🤗
