### ISSUE TITLE
Publish a new 1.1.0 version

### ISSUE THREAD

**Issue by etorreborre** [hedgehogqa/haskell-hedgehog#440]
Would it be possible to publish a new version with the latest change, like the deprecation of `HTraversable`? Thank you

**Comment by kozross** [comment]
This is quite germane, as the current Hackage version doesn't support GHC 9.2.

**Comment by chris-martin** [comment]
What is the obstacle to a release? Is there anything that can be done to help?

**Comment by ocharles** [comment]
I think a lack of time. I would happily join the team to help with routine work like releases, if it would help!

**Comment by chris-martin** [comment]
Same, I'd love to be able to do some of the mundane work.

**Comment by jacobstanley** [comment]
Thanks for your patience all 🙏

[hedgehog-1.1](https://hackage.haskell.org/package/hedgehog-1.1) has now been published.

You are right @ocharles, December was a bit of rough month for me so I didn't have time to look at this. I'd be open to having someone help with this kind of routine stuff.
