### ISSUE TITLE
Compatibility with text-2.0

### ISSUE THREAD

**Issue by sjakobi** [hedgehogqa/haskell-hedgehog#443]
See https://hackage.haskell.org/package/text-2.0/changelog.

Could you upload a compatible version? Thanks! :)

**Comment by jacobstanley** [comment]
I attempted to do this and we need [wl-pprint-annotated](https://hackage.haskell.org/package/wl-pprint-annotated) and [concurrent-output](https://hackage.haskell.org/package/concurrent-output) to be updated also.

Also: UTF-8 amazing! I never thought that would actually happen 🎉

**Comment by ysangkok** [comment]
I have sent a patch to Joey (maintainer of concurrent-output) and made a PR for the other:

* minad/wl-pprint-annotated/pull/9

**Comment by kozross** [comment]
@jacobstanley I think `concurrent-output` has also moved to support `text-2.0`.

**Comment by ysangkok** [comment]
@jacobstanley The two dependencies you mentioned have been updated and they now support text 2.0.

**Comment by gwils** [comment]
Can you please release this as a metadata revision or new version?
