### ISSUE TITLE
Subset generator

### ISSUE THREAD

**Issue by chris-martin** [hedgehogqa/haskell-hedgehog#444]
I'd like to propose adding a function to `Hedgehog.Gen`:

```haskell
subset :: MonadGen m => Set a -> m (Set a)
subset = fmap Set.fromList . subsequence . Set.toAscList
```

This is something I find myself doing somewhat often, and for some reason I have a hard time remembering that `subsequence` is the way to go about it.

**Comment by jacobstanley** [comment]
I like it, I'd accept a PR 👍

(also can it be `Set.fromAscList`)

**Comment by chris-martin** [comment]
Oh cool, I think you're right. Just to make sure, `subsequence` generates a list where the elements are in the same order but not necessarily contiguous in the input list, right? So for example, `Gen.subsequence (1 .. 5)` could generate `[2, 4]` but not `[4, 2]`? (I might also submit a doc PR on that to clarify.)

**Comment by chris-martin** [comment]
Actually, better yet, it can be `Set.fromDistinctAscList`.
