### ISSUE TITLE
Is there a way of limiting retries from within a generator?

### ISSUE THREAD

**Issue by AriFordsham** [hedgehogqa/haskell-hedgehog#458]
I would like to be able to write a generator that restricts the number of times a shrink can be retried.

The API has only `withRetries` that works on a `Property`.

Is there a way of doing this (or equivalent) from within the `Gen` monad?

**Comment by TysonMN** [comment]
It sounds to me like you are asking for a particular solution instead of describing your problem (aka the [XY problem] (https://en.wikipedia.org/wiki/XY_problem)).

Can you describe your problem?
