### ISSUE TITLE
Is there a way to 'catch' test failure in the `PropertyT` monad?

### ISSUE THREAD

**Issue by AriFordsham** [hedgehogqa/haskell-hedgehog#460]
I would like to write a property combinator that wraps other properties, and performs further actions, even if the test fails. A simple example would be a `shouldFail` combinator

```
shouldFail :: PropertyT m a -> PropertyT m ()
```

That succeeds only if its argument fails.

Is this possible, even if it means using internal Hedgehog APIs?

**Comment by ocharles** [comment]
I think you can just use https://hackage.haskell.org/package/lifted-base-0.2.3.12/docs/Control-Exception-Lifted.html#v:onException

**Comment by AriFordsham** [comment]
Not so. That will catch exceptions thrown within a test. It will not catch test failure (e.g. `assert False`) which does not throw an exception, but rather embeds a failure value somewhere in the monad stack.

**Comment by AriFordsham** [comment]
```
check . property $ catch (assert False) (\(_ :: SomeException) -> assert True)
```
with `catch` from `Control.Exception.Lifted` causes test failure.

**Comment by AriFordsham** [comment]
The only way I succeeded was:
```haskell
shouldFail :: (Monad m) => PropertyT m a -> PropertyT m ()
shouldFail =
  PropertyT 
    . TestT 
    . ExceptT 
    . fmap (either (const $ Right ()) (const $ Left (Failure (getCaller callStack) "" Nothing))) 
    . runExceptT 
    . unTest 
    . unPropertyT
```
```
check . property $ shouldFail (assert False)
  ✓ <interactive> passed 100 tests.
True
```
```
check . property $ shouldFail (assert True)
  ✗ <interactive> failed 
    after 1 test.
  
    This failure can be reproduced by running:
    > recheck (Size 0) (Seed 6586435806264587896 4590598605409345205) <property>
  
False
```
