### ISSUE TITLE
Provide MonadUnliftIO instance for PropertyT?

### ISSUE THREAD

**Issue by kokobd** [hedgehogqa/haskell-hedgehog#470]

**Comment by ocharles** [comment]
I'm not sure such an instance exists. `MonadUnlirtftIO` is for monads essentially isomorphic to ReaderT, and I'd be surprised if either `PropertyT` or `TestT` are

**Comment by endgame** [comment]
```haskell
newtype PropertyT m a = PropertyT { unPropertyT :: TestT (GenT m) a }
newtype TestT m a = TestT { unTest :: ExceptT Failure (Lazy.WriterT Journal m) a }
```
Yeah, that's going to be impossible I'm afraid.
