### ISSUE TITLE
Support GHC-9.6 (template-haskell-2.20)

### ISSUE THREAD

**Issue by ysangkok** [hedgehogqa/haskell-hedgehog#480]
The current revision of hedgehog-1.2 rejects template-haskell-2.20 which is the version shipped with GHC-9.6. It would be nice if hedgehog supported this version of template-haskell such that this new GHC version is supported.

**Comment by ysangkok** [comment]
This depends on #478

**Comment by moodmosaic** [comment]
Thank you, @ysangkok. #478 is merged now. Feel free to close this, or keep open until the release goes out.
