### ISSUE TITLE
Running without Template Haskell

### ISSUE THREAD

**Issue by chris-martin** [hedgehogqa/haskell-hedgehog#49]
I don't have a fundamental objection to template haskell, but what I do have is a list of `Property` and I'm not sure how to check them all in parallel.

**Comment by chris-martin** [comment]
Oh nevermind, I see you've already implemented something very much like I was about to propose. Is it suitable for release?

**Comment by jystic** [comment]
It is ready for release, I plan to do one on the weekend, probably after implementing the stuff we're talking about in https://github.com/hedgehogqa/haskell-hedgehog/issues/51
