### ISSUE TITLE
`evalMaybeM` doesn't produce the correct callstack

### ISSUE THREAD

**Issue by ocharles** [hedgehogqa/haskell-hedgehog#497]
If we use `evalMaybeM` we get `the value was Nothing`, but it's not attached to the line calling `evalMaybeM`. I think `evalMaybeM` needs a `withFrozenCallStack`, but I'm not quite sure where - probably around the whole definition?

**Comment by moodmosaic** [comment]
Hmm... 🤔 Probably around the whole definition, so it will freeze the call stack before the `failWith` function is called, ensuring that the stack trace points to the location where `evalMaybeM` is called, rather than inside the implementation of `evalMaybeM`.
