### ISSUE TITLE
How to write a `bracketProperty`?

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#498]
I am trying (and failing) to write something with a type signature (ignoring the constraints for now) something like:
```
bracketProperty
    => m a       -- ^ computation to run first ("acquire resource")
    -> (a -> m b) -- ^ computation to run last ("release resource")
    -> (a -> Property) -- ^ The property test to run in-between
    -> Property
```
Hopefully what I want is completely obvious from the type. Any clues?

**Comment by ocharles** [comment]
What test driver are you using? If you are using `tasty`, `withResource` would probably be the correct tool here. For `hspec`, `around` would probably be what you want.

**Comment by erikd** [comment]
I am just using the Hedgehog test driver. An only one of the tests needs this resource, so I was hoping to do this within that single test.

**Comment by ocharles** [comment]
Ok, it may be worth upgrading to one of the mentioned drivers. Other than that, `bracket` around `check` might be your best option. `PropertyT IO` also gives you access to `MonadBaseControl` which I think might also give you a lifted `bracket`, but I'd personally aim to do this resource allocation outside of `Property`

**Comment by erikd** [comment]
Thanks @ocharles , using `PropertyT` was a great tip.

I now have  :

```
-- Slightly modified version of `withTempDirectory` from the `temporary` package.
propertyWithTempDirectory
    :: FilePath -> String -> (FilePath -> PropertyT IO a) -> PropertyT IO a
propertyWithTempDirectory targetDir template =
    bracket
      (Hedgehog.evalIO (createTempDirectory targetDir template))
      (Hedgehog.evalIO . ignoringIOErrors . removeDirectoryRecursive)
  where
    ignoringIOErrors :: MonadCatch m => m () -> m ()
    ignoringIOErrors ioe = ioe `catch` (\e -> const (pure ()) (e :: IOError))
```
and it fits into my existing tests perfectly. And the test passes.

**Comment by erikd** [comment]
I spoke too soon:
```
    • No instance for (Hedgehog.MonadGen (PropertyT IO))
        arising from a use of ‘Gen.list’
```
Looks like I may need to look into `tasty-hedgehog` or similar.

**Comment by ocharles** [comment]
For that you want `forAll` - right? That lifts `Gen` into `Property`

**Comment by erikd** [comment]
OMFG, of course. That was before coffee and I have not got back to that yet.
