### ISSUE TITLE
Support ghc-9.8.1

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#502]
This builds with the appropriate `allow-newer` so a Hackage metadata update would be sufficient.
```
> (cd hedgehog && cabal outdated)
Outdated dependencies:
bytestring >=0.10 && <0.12 (latest: 0.12.0.2)
containers >=0.4 && <0.7 (latest: 0.7)
deepseq >=1.1.0.0 && <1.5 (latest: 1.5.0.0)
primitive >=0.6 && <0.9 (latest: 0.9.0.0)
template-haskell >=2.10 && <2.21 (latest: 2.21.0.0)
text >=1.1 && <2.1 (latest: 2.1)
containers >=0.4 && <0.7 (latest: 0.7)
text >=1.1 && <2.1 (latest: 2.1)

> (cd hedgehog-example/ && cabal outdated)
Outdated dependencies:
containers >=0.4 && <0.7 (latest: 0.7)
template-haskell >=2.10 && <2.21 (latest: 2.21.0.0)
text >=1.1 && <2.1 (latest: 2.1)

> (cd hedgehog-dieharder/ && cabal outdated)
Outdated dependencies:
bytestring >=0.10.4.0 && <0.12 (latest: 0.12.0.2)

> (cd hedgehog-test-laws/ && cabal outdated)
Outdated dependencies:
checkers >=0.5 && <0.5.5 (latest: 0.6.0)
tasty >=1.2 && <1.3 (latest: 1.5)
tasty-expected-failure >=0.11 && <0.12 (latest: 0.12.3)
transformers >=0.5 && <0.6 (latest: 0.6.1.1)
```
Let me know if you would prefer a PR.

**Comment by ysangkok** [comment]
This can now be closed since a fix was pushed to the main branch.

**Comment by erikd** [comment]
Released to Hackage?

**Comment by ysangkok** [comment]
@moodmosaic , would it be possible to make a revision with the new version bounds?

**Comment by tomjaguarpaw** [comment]
I'd be surprised if it was possible just to revise bounds, given that we found that a warning needed to be disabled (https://github.com/hedgehogqa/haskell-hedgehog/pull/504/files). In fact, I'm surprised that @erikd says it builds with `allow-newer` in his original comment. I don't understand how that can be.

**Comment by moodmosaic** [comment]
> Released to Hackage?

Not released yet.

Perhaps during the day or during the weekend. But as a regular release as I’m unsure if a revision works in this case.

I'd be nice if we can somehow automate hackage releases.

**Comment by ysangkok** [comment]
@tomjaguarpaw 

> I'd be surprised if it was possible just to revise bounds, given that we found that a warning needed to be disabled
>  In fact, I'm surprised that @erikd says it builds with allow-newer in his original comment. I don't understand how that can be.

The `-Werror` flag is set in `cabal.project`, which is a file that is not really part of the `hedgehog` package. This file is most commonly loaded when developing `hedgehog` itself. If you build `hedgehog` as a dependency, `cabal.project` will not be used.

**Comment by tomjaguarpaw** [comment]
Ah, got it! In that case @moodmosaic, making revisions on Hackage that reflect the version bumps in https://github.com/hedgehogqa/haskell-hedgehog/pull/504/files is sufficient.

**Comment by moodmosaic** [comment]
Published [new revision](https://hackage.haskell.org/package/hedgehog-1.4/revisions/) for [hedgehog-1.4](https://hackage.haskell.org/package/hedgehog-1.4) 🦔  
 It will be available as soon as package index is updated (e.g. cabal update).

Thank you, @ysangkok, @tomjaguarpaw, @erikd.

**Comment by erikd** [comment]
This can be closed.
