### ISSUE TITLE
accept primitive-0.9

### ISSUE THREAD

**Issue by ysangkok** [hedgehogqa/haskell-hedgehog#508]
This new breaking release of primitive is currently excluded by bounds in the hedgehog package.

[Changelog for primitive-0.9](https://hackage.haskell.org/package/primitive-0.9.0.0/changelog)

Stackage issue:
* https://github.com/commercialhaskell/stackage/issues/7138

**Comment by moodmosaic** [comment]
Thanks! If you open a PR we can merge it and make a hackage revision.

**Comment by moodmosaic** [comment]
See https://github.com/hedgehogqa/haskell-hedgehog/pull/509#issuecomment-1920049732 for the newly published revision. 🎉
