### ISSUE TITLE
Relax upper bound on `time` to `< 1.15`

### ISSUE THREAD

**Issue by tomjaguarpaw** [hedgehogqa/haskell-hedgehog#512]
This succeeds, so I guess a Hackage revision should relax the bound on `time` to `< 1.15` (currently it's `< 1.13`).

* `cabal repl -z -b hedgehog -b 'time>=1.14' --allow-newer=time`

**Comment by moodmosaic** [comment]
Thank you! If you open a PR, we can merge it and do a hackage revision right after.

**Comment by tomjaguarpaw** [comment]
OK: https://github.com/hedgehogqa/haskell-hedgehog/pull/513
