### ISSUE TITLE
Allow `hspec-hedgehog` to produce more compact output

### ISSUE THREAD

**Issue by sol** [hedgehogqa/haskell-hedgehog#522]
This requires:
- [x] #519
- [x] #520
- [x] #523
- [x] #524

Before:
![before](https://github.com/hedgehogqa/haskell-hedgehog/assets/461132/315b38ea-8c80-4ee7-87cc-57a896415c36)

After:
![after](https://github.com/hedgehogqa/haskell-hedgehog/assets/461132/5984c2e6-6bd8-4fdf-8afe-c6fbd5c87ffe)

**Comment by sol** [comment]
@moodmosaic that's all that I have on my wish list.  After that, I'm pretty happy with the output.

**Comment by moodmosaic** [comment]
> @moodmosaic that's all that I have on my wish list. After that, I'm pretty happy with the output.

Planning for a release after #525. 🎉

**Comment by sol** [comment]
https://github.com/hedgehogqa/haskell-hedgehog/pull/519#issuecomment-2105614330

@ChickenProp e could still include the "shrink path", I guess.

From what I understand, this only affects performance. Do you regularly run into situations where this makes a practical difference?

**Comment by ChickenProp** [comment]
I regularly run into situations where it makes a big practical difference to performance :p Like, it can be several minutes versus a few seconds.

But also, it can really help debugging. I often use print or trace statements to help, and if I don't use the shrink path, the last lines of output are often from tests that passed. Or I'll do stuff with a database, and then the database state at the end has been changed by tests that passed. With the shrink path, I know the last attempt failed, which is super helpful. (If I want that with quickcheck, I kind of have to binary search to find the lowest `--qc-max-shrinks` value that gives the full number of successful shrinks.)

(I did notice that the shrink path is also visible at the top of the failure message, so there's that too. But it's a lot easier for me if it's at the bottom.)

**Comment by sol** [comment]
> I did notice that the shrink path is also visible at the top of the failure message, so there's that too.

It's gone now, see screens, but we could bring it back.

 > But it's a lot easier for me if it's at the bottom.

Given that the output will be much more compact now (mostly due to https://github.com/hedgehogqa/haskell-hedgehog/pull/505), does this still matter?

**Comment by ChickenProp** [comment]
> It's gone now, see screens, but we could bring it back.

Oh, right. My inclination would be to leave it, or at any rate not to disable it along with the `recheckAt` message. But for myself, I'm still likely to re-enable the `recheckAt` message, so as long as I can do that in my environment and forget about it, it's not gonna make a big difference to me.

> Given that the output will be much more compact now (mostly due to #505), does this still matter?

I think so, yeah. Sometimes there'll be annotations which presumably make the output big again, but even apart from that, I think it's easier to visually scan for if I know it's near the bottom.

**Comment by moodmosaic** [comment]
@sol, @ChickenProp, happy to plan for a release and/or also wait until this is resolved/closed. Let me know if there's anything I can do to help.

**Comment by sol** [comment]
@ChickenProp  we will keep the shrink path for now #531.  The long-term plan is to add more options to Hspec to allow you to get the full reproduce message and possibly also to allow skipping to specific hedgehog tests.

**Comment by sol** [comment]
@moodmosaic after #531 I think we are good to go.

**Comment by sol** [comment]
> but that doesn't need to be hedgehog's problem. In which case maybe this discussion belongs at [hspec/hspec-hedgehog#35](https://github.com/hspec/hspec-hedgehog/pull/35)?

That was my line of thought. `hedgehog` now offers enough flexibility to allow `hspec-hedgehog` to take advantage of it in various ways.

> At any rate, I think this is a clear improvement to hedgehog as-is, and I think a release after #531 makes sense.

Great 👍  @moodmosaic I guess that means "yes, we can move forward with a release" after #531.

**Comment by moodmosaic** [comment]
@sol, @ChickenProp, thank you for the feedback. 💯 #531 is just merged 🎉

**Comment by moodmosaic** [comment]
Can be closed once we close #534.

**Comment by moodmosaic** [comment]
@sol, thank you for your work on this. Closing as per #534. Feel free to re-open if/when needed.
