### ISSUE TITLE
Hackage metadata edit on containers dependency.

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#532]
The repo has:
```
    , containers                      >= 0.4        && < 0.8
```
but the latest revision on Hackage still has `containers (>=0.4 && <0.7)`.

Probably worth ensuring all the other dependencies align with the repo as well.

**Comment by moodmosaic** [comment]
Thanks! Though I don't see `0.8` in the latest/current [hedgehog.cabal](https://github.com/hedgehogqa/haskell-hedgehog/blob/06fef4044356e9fe6a19807a9f925e20b843b593/hedgehog/hedgehog.cabal), I see `0.7` which is what I see also on hackage. Perhaps you're on a branch?

**Comment by erikd** [comment]
Somehow I messed up not exactly sure how. I will submit a new PR with those version bumps.
