### ISSUE TITLE
CHANGELOG.md: Links to corresponding PRs for Version 1.5 are broken

### ISSUE THREAD

**Issue by sol** [hedgehogqa/haskell-hedgehog#535]
https://github.com/hedgehogqa/haskell-hedgehog/blob/master/CHANGELOG.md

**Comment by moodmosaic** [comment]
Thank you. This was my mistake. It can be fixed by https://github.com/hedgehogqa/haskell-hedgehog/pull/536.

**Comment by moodmosaic** [comment]
This issue is fixed by #536. Closing.

@sol, do you think it's worth fixing on Hackage? I believe it requires a new release since only metadata can be revised.

**Comment by sol** [comment]
I don't think it makes sense to have change logs, read me, etc. on Hackage in the first place, for exactly that reason. Things are easier if you have one authoritative source. From my perspective this is just a needless time sink that "steals away" time that could be better used for development.

**Comment by moodmosaic** [comment]
Agreed 👍
