### ISSUE TITLE
Generating functions?

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#62]
I need to be able to generate arbitrary functions. Is that something that should be part of Hedgehog or would that be better as a separate package?

And how much of https://hackage.haskell.org/package/QuickCheck-2.9.2/docs/Test-QuickCheck-Function.html do you think can be reused/re-purposed?

**Comment by erikd** [comment]
Problems are discussed here : https://www.reddit.com/r/haskell/comments/646k3d/ann_hedgehog_property_testing/dg1485c/

**Comment by jystic** [comment]
> Is that something that should be part of Hedgehog or would that be better as a separate package?

It should be part of Hedgehog eventually, there are a few challenges though, as noted by Koen.

Firstly we need something like `CoArbitrary`, but I'd like to avoid type classes in Hedgehog, so it requires a bit of thinking. Second, we need something like [promote](https://hackage.haskell.org/package/QuickCheck-2.9.2/docs/Test-QuickCheck-Gen-Unsafe.html#v:promote).

Either that, or if it's not possible we might need to think of a different approach.

**Comment by erikd** [comment]
For my needs I wrote some [data types](https://github.com/erikd/nested-resource/blob/master/nested-resource/test/Test/Control/Monad/NestedResource.hs#L26-L57) and [and interpretter](https://github.com/erikd/nested-resource/blob/master/nested-resource/test/Test/Control/Monad/NestedResource.hs#L103-L116) which was easy enough for my use case.

**Comment by jystic** [comment]
I was discussing this with @thumphries and @damncabbage last night, one way to generate a function for simple cases would be to generate a `Data.Map` using `Gen.map`.

You could then lift the map to a function:
```hs
fromMap :: v -> Map k v -> k -> v
fromMap defaultValue kvs k =
  case Map.lookup k kvs of
    Nothing ->
      defaultValue
    Just value ->
      value
```

**Comment by bitemyapp** [comment]
https://github.com/bitemyapp/hedgehog-checkers/blob/master/hedgehog-checkers/src/Hedgehog/Checkers/Ugly/Function/Hack.hs

gooby pls

**Comment by LightAndLight** [comment]
Hey mates, here's a working (as far as I can tell) prototype.

https://github.com/lightandlight/hedgehog-fn

I'd appreciate any feedback :)

Is this something you'd want included in this codebase, or should it be kept separate?

**Comment by mitchellwrosen** [comment]
@LightAndLight Nice, I'm interested in seeing this merged with `hedgehog` proper. I don't know much about function generation but once concern mentioned above was introducing type classes into hedgehog.

Can you explain what this means in the documentation of `Vary`?

> While technically there are many possible co-generators for a given type, we don't get any benefit from caring.

Why don't we get any benefit from caring? For example, I see a co-generator instance

```
instance Vary a => Vary (Maybe a)
```

Does this mean co-generating a `Maybe a` input will be `Nothing` 50% of the time? If so, that's a departure from hedgehog, where everything happens at the value level.

**Comment by thumphries** [comment]
> I'm interested in seeing this merged with hedgehog proper. I don't know much about function generation but one concern mentioned above was introducing type classes into hedgehog.

We ended up discussing this on Slack and the consensus was to keep it as a separate library for various reasons. We can always link to it from the documentation however so it is easier to discover.

**Comment by thumphries** [comment]
Going to close this as it's not quite an open question anymore. There's a [good usable library on Hackage](https://hackage.haskell.org/package/hedgehog-fn) and we've chosen not to add anything else to Hedgehog any time soon, so the only missing piece is to communicate this in the docs.

Created #228 in the meantime, as a landing pad for others asking this question

**Comment by LightAndLight** [comment]
Replying here for completeness (but let's take any further discussion out of the closed issue)

@mitchellwrosen Co-generators don't influence the random distribution. They are an implementation detail to make sure the functions are sufficiently random, but still deterministic. Hopefully https://kseo.github.io/posts/2016-12-14-how-quick-check-generate-random-functions.html helps explain it.

I've kept the type classes as minimal and benign as possible, because that's one of the reasons I use hedgehog in the first place.
