### ISSUE TITLE
What's the easiest way to "look at" a generator?

### ISSUE THREAD

**Issue by chris-martin** [hedgehogqa/haskell-hedgehog#66]
When I'm writing a `Gen` I'd like to have a quick way in GHCI to generate some values just to do a sanity check and make sure the distribution looks reasonable. Is there already some intended way to do that?

**Comment by moodmosaic** [comment]
See *Sampling Generators* section [here](http://hackage.haskell.org/package/hedgehog-0.1/docs/Hedgehog-Gen.html#v:Gen).

**Comment by chris-martin** [comment]
Ah, sorry - I saw the "sampling" section under "internal" and assumed that was it.
