### ISSUE TITLE
Lift the upper bounds of concurrent-output and wl-pprint-annotated

### ISSUE THREAD

**Issue by amarpotghan** [hedgehogqa/haskell-hedgehog#79]
I would send a PR if you agree with the following:

```
wl-pprint-annotated  >= 0.0 && < 0.2
concurrent-output   >= 1.7  && < 2.0
```

That way both libraries will be upgraded to the latest versions. What do you think?

**Comment by jystic** [comment]
Yeah, that's no problem, I'll always be ok with widening bounds as long as everything still works
