### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by tfausak** [hedgehogqa/haskell-hedgehog#87]
It would be nice if Hedgehog was available on Stackage. https://github.com/fpco/stackage/#add-your-package

**Comment by moodmosaic** [comment]
I think it makes sense to make Hedgehog available on Stackage, because currently you have to specify it in the `extra-deps` section of `stack.yaml`:

```diff
diff --git a/Haskell/stack.yaml b/Haskell/stack.yaml
index 8647a74..c9186ed 100644
--- a/Haskell/stack.yaml
+++ b/Haskell/stack.yaml
@@ -39,7 +39,9 @@ packages:
 - '.'
 # Dependency packages to be pulled from upstream that are not in the resolver
 # (e.g., acme-missiles-0.3)
-extra-deps: []
+extra-deps:
+- hedgehog-0.2
+- wl-pprint-annotated-0.0.1.4
 
 # Override default flag values for local packages and extra-deps
 flags: {}
```

**Comment by jystic** [comment]
I'm OK with this, looking at those `extra-deps` I presume that means we need get `wl-pprint-annotated` added as well?

**Comment by tfausak** [comment]
wl-pprint-annotated is actually already on Stackage: https://www.stackage.org/package/wl-pprint-annotated

**Comment by moodmosaic** [comment]
>wl-pprint-annotated is actually already on Stackage

It is, but I wanted to demonstrate how the `stack.yaml` looks like until we get Hedgehog on Stackage 😃 

As an example, for Hedgehog 0.2 (currently not on Stackage), if I remove `wl-pprint-annotated-0.0.1.4` from the `extra-deps` section of `stack.yaml`, I get this:

```
$ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hedgehog-0.2:
    wl-pprint-annotated must match >=0.0 && <0.1, but the stack configuration has no
    specified version (latest applicable is 0.0.1.4)
needed due to BookingApi-0.1.0.0 -> hedgehog-0.2

Recommended action: try adding the following to your extra-deps in ~/../stack.yaml:
- wl-pprint-annotated-0.0.1.4

You may also want to try the 'stack solver' command
Plan construction failed.
```

**Comment by tfausak** [comment]
Which resolver are you using? The following configuration builds on my machine:

``` yaml
# stack.yaml
resolver: lts-8.0
extra-deps: [ hedgehog-0.2.2 ]

# package.yaml
library: { dependencies: hedgehog }
```

It was added to Stackage in https://github.com/fpco/stackage/pull/2092.

**Comment by MichaelXavier** [comment]
Is there anything us bystanders can do to help this along? If you don't have to specify any extra-deps for the project in the latest LTS, don't we just need to PR stackage to add it and call it good?

**Comment by jystic** [comment]
I'm completely ok with someone else adding it stackage, I haven't added a package there before so I'm just unsure what needs to happen is all.

**Comment by tfausak** [comment]
You have to open a pull request against the Stackage repository. It would look a lot like this: https://github.com/fpco/stackage/pull/2639/files

**Comment by jystic** [comment]
Ah, is that it?

**Comment by tfausak** [comment]
Yup! It's pretty easy. Even easier when you already maintain at least one package. Then the pull requests look like this: https://github.com/fpco/stackage/pull/2248/files

**Comment by jystic** [comment]
https://github.com/fpco/stackage/pull/2653

**Comment by jystic** [comment]
Done 🎉
