### ISSUE TITLE
Group creation requires import of Hedgehog.Internal.Property (GroupName (..), PropertyName (..))

### ISSUE THREAD

**Issue by berewt** [hedgehogqa/haskell-hedgehog#88]
This example of the README can't compile:

~~~haskell
tests :: IO Bool
tests =
  checkParallel $ Group "Test.Example" [
      ("prop_reverse", prop_reverse)
    ]
~~~

As group name and property name are newtypes, it should be something like:

~~~haskell
tests :: IO Bool
tests =
  checkParallel $ Group (GroupName "Test.Example") [
      (PropertyName "prop_reverse", prop_reverse)
    ]
~~~

However, this small change won't fix it if we don't import `Hedgehog.Internal.Property (GroupName (..), PropertyName (..))` , as the none of these consturctors are re-exported by `Hedgehog` root package.

Solutions I can imagine:
- reexport the GroupName and PropertyName constructor
- create a `group` function that encapsulates the names (i.e.: `group :: String -> [(String, Property)]`)
- get rid of the newtypes.

I'd be glad to create a pull request for this issue when the solution will be chosen.

**Comment by jystic** [comment]
I don't mind exporting the constructors, but they aren't necessary, the example code should work if you enable `OverloadedStrings`.

So either put `{-# LANGUAGE OverloadedStrings #-}` at the top of your `.hs` file, or add `extensions: OverloadedStrings` to your `.cabal` file.

**Comment by berewt** [comment]
Oh, I totally forgot to use OverloadedStrings, I should have thought about it! Thanks. It is sufficient, yes.

**Comment by jystic** [comment]
My bad, I notice that it's missing from the docs / readme!
