### ISSUE TITLE
Top-level test runner

### ISSUE THREAD

**Issue by erikd** [hedgehogqa/haskell-hedgehog#97]
Would be nice to have something like [disorderMain](https://github.com/ambiata/disorder.hs/blob/72309ceaec55a47d0d2577fa3ab12f087e377ddd/disorder-core/src/Disorder/Core/Main.hs#L16) in Hedgehog. 

Basically just something like:
```
runTests :: [IO Bool] -> IO ()
runTests tests = do
  hSetBuffering stdout LineBuffering
  hSetBuffering stderr LineBuffering
  results <- sequence tests
  unless (and results)
    exitFailure
```

**Comment by thumphries** [comment]
> Does hedgehog have something like disorderMain?

Nope. Maybe it should? I've written the function above a dozen times now.

Alternative is to emphasise use through Tasty or HSpec, Hedgehog's test runner is arguably a bit better and I'd rather use it directly.

**Comment by chris-martin** [comment]
As somebody involved in writing a lot of beginner Haskell tutorials, I'd really like to see this happen. We'd like to use Hedgehog as our standard testing recommendation for beginners, but `sequence`, `exitFailure`, and line buffering are a lot to have to explain upfront before you can even get started. We can't ask people to write a test runner that uses `sequence` while we're still teaching about `fmap`. Having to recommending a second test package to get the runner also seems overly cumbersome; do you not desire Hedgehog to be quickly usable "out of the box," so to speak?

**Comment by thumphries** [comment]
> Perhaps support for Hedgehog with the 'detailed' Cabal testing interface is what we actually need.

`detailed` is not widely used, the community mostly just continued using `hspec` / `tasty`. So I wouldn't put too much weight on that, though supporting it might encourage use. Last I looked, `cabal new-test` didn't support it yet! It might now, not sure.

It's not that we want to screw over `teh beginners`; we spent quite a while trying to settle on the right code to include, but every choice we made seemed adhoc and surprising, so we slept on it.

In general we've pushed adhoc experiments out of `hedgehog` proper, like `hedgehog-fn`. Packages that prove truly indispensable can be brought back into the main library if necessary, though we prefer to distribute the maintenance burden. A second library that we link to in documentation is probably the only resolution for this one.

> do you not desire Hedgehog to be quickly usable "out of the box," so to speak?

> We can't ask people to write a test runner that uses `sequence` while we're still teaching about `fmap`

Of course we'd like it to be as easy as possible to use! We also want it to be more or less permanent with few API changes or deletions, so we are a bit hesitant to merge grab bags of code to support Cabal's current operational model. These things are easy to add and impossible to remove, so anything that doesn't have full consensus basically shouldn't go in.

In the meantime, there are a bunch of ways you can run tests with little fuss in a tutorial environment, e.g.

- Run the tests in GHCi / ghcid with `check` / `checkSequential` (this is the nicest way to write tests)
- Include the boilerplate in your tutorial template
- Write the function for a single test suite; `if success then exitSuccess else exitFailure`
- Write the function using `for` to avoid `sequence`
- Use `tasty` or `hspec`
- Let them inline the code and explain it later

**Comment by chris-martin** [comment]
I get the feeling there's something I'm missing out on here. I was under the impression that exitcode-stdio-1.0 has been around for a long time and was showing no signs of disappearing any time soon. Is that wrong?

**Comment by thumphries** [comment]
To restate: as a group we were not happy with any of the proposed implementations. We found each alternative was surprising to the user in one or more ways. We don't want to release code that we aren't happy with as it restricts our ability to do it properly in the future.

PRs of this nature are still welcome but will need to be ruled on by @jystic when he gets back. Given that the code is useful for QuickCheck too and there's potential to support `detailed` and test suite discovery, a new package makes the most sense.
